### PR TITLE
DX: Assert - use assertSame over assertEquals

### PR DESCRIPTION
**Pull request by keradus**

### CODE REVIEW

**Comment by sebastianbergmann** [comment]
I am not convinced that this does not have any unexpected side effects.

**Comment by keradus** [comment]
assertEquals -> assertSame is changed only for comparing strings and ints, works the same

about dropping `if (\is_bool($expected) && \is_bool($actual)) {` - I found no reason why it's there, `IsIdentical` works good for comparing booleans. No test failed as well...

**Comment by keradus** [comment]
thanks for merging :+1:

**Comment by keradus** [comment]
@sebastianbergmann , sure I will !
I'm a bit overwhelmed right now, sorry for delays on this on other topics...

**Pull request merged**
