### PR TITLE
Remove TestableCliTestDoxPrinter

### PR DESCRIPTION
**Pull request by janedbal**
As found in https://github.com/sebastianbergmann/phpunit/issues/5681, this class extend non-existing class

### CODE REVIEW

**Comment by sebastianbergmann** [comment]
Is `main` the earliest branch where this file can be deleted?

**Comment by janedbal** [comment]
I dont yet see into the branching here, I can try to find the commit where the parent class was deleted if that helps.

**Comment by janedbal** [comment]
Deleted here: https://github.com/sebastianbergmann/phpunit/commit/4605ade88b2e91228fba1b34de766bb0008b8a4c

**Comment by janedbal** [comment]
So it can be deleted even in 10.5 branch imo.

**Comment by sebastianbergmann** [comment]
Cherry-picked into `10.5` and merged to `main` from there. Thanks!

**Pull request closed without merging**
