### PR TITLE
Fix parsing of single line DocBlock

### PR DESCRIPTION
**Pull request by ostrolucky**
See #4692

### CODE REVIEW

**Comment by ostrolucky** [comment]
Test failures don't seem related

**Comment by sebastianbergmann** [comment]
> Test failures don't seem related

No, they're not. See #4694.

**Comment by sebastianbergmann** [comment]
Thanks!

**Comment by ostrolucky** [comment]
Thx for merge. Please don't forget to backport to 8.5

**Comment by sebastianbergmann** [comment]
I backported this to PHPUnit 8.5 and PHPUnit 9.5 before I closed #4692.

**Pull request merged**
