### PR TITLE
Assert::assertNotEquals - fix BC

### LINKED ISSUE #3176: 7.2.5 breaks BC !
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 7.2.5
| PHP version         | 7.1, for example
| Installation Method | Composer, but doesn't matter

newly released 7.2.5 breaks BC:
https://github.com/sebastianbergmann/phpunit/commit/bcb4c788c7872cd2f885ccf50285f6feb7cfff1a#diff-9ae7a972d07df5f73629d5d315bf405aR521

formal declaration of method changed:
```diff
-    public static function assertNotEquals($expected, $actual, string $message = '', $delta = 0.0, $maxDepth = 10, $canonicalize = false, $ignoreCase = false): void
+    public static function assertNotEquals($expected, $actual, string $message = '', float $delta = 0.0, int $maxDepth = 10, bool $canonicalize = false, bool $ignoreCase = false): void
```

for that, my integration crashes on incompatible method headers:
https://travis-ci.org/FriendsOfPHP/PHP-CS-Fixer/jobs/394945074#L655
```
PHP Fatal error:  Uncaught Declaration of
PHPUnitGoodPractices\Traits\IdentityOverEqualityTrait::assertNotEquals($expected, $actual, string $message = '', $delta = 0, $maxDepth = 10, $canonicalize = false, $ignoreCase = false): void
should be compatible with
PHPUnit\Framework\Assert::assertNotEquals($expected, $actual, string $message = '', float $delta = 0, int $maxDepth = 10, bool $canonicalize = false, bool $ignoreCase = false): void
```

### PR DESCRIPTION
**Pull request by keradus**
Closes #3176

### CODE REVIEW

**Comment by sebastianbergmann** [comment]
Are you sure that this is the only part of bcb4c788c7872cd2f885ccf50285f6feb7cfff1a that needs to be reverted?

**Comment by keradus** [comment]
I reviewed whole commit manually, didn't found anything else.
also, with this patch tests are not crashing on my project anymore

**Comment by keradus** [comment]
Thanks for quick merging, appreciating ;)
Hoping for new 7.2 release soon ;)

**Comment by keradus** [comment]
Thanks for the release @sebastianbergmann !

**Pull request merged**
