### PR TITLE
Removed `strict` attribute from schema file

### PR DESCRIPTION
**Pull request by fabiang**
Removed `strict` attribute from schema file

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Tests faling?

**Comment by fabiang** [comment]
@GrahamCampbell: Not my fault, as far as I can tell. `xmllint` exits with code 0.

**Comment by sebastianbergmann** [comment]
The PHP 7 build on Travis CI keeps failing. Works fine locally. No clue what is going on there.

**Comment by sebastianbergmann** [comment]
Merged manually, thanks.

**Pull request closed without merging**
