### PR TITLE
Remove class name as CLI option

### PR DESCRIPTION
**Pull request by realFlowControl**
This pull request removes the class name as CLI option as stated in #4012

### CODE REVIEW

**Comment by sebastianbergmann** [comment]
Looks good so far. Now we only need to remove the actual code :) Do you know when you will have time to finish this? Would be great to have to this ready by the end of next week. Thanks!

**Comment by flow-control** [comment]
End of next week sound feasible as i was planing to invest more time this weekend

**Comment by flow-control** [comment]
Hey @sebastianbergmann,

not yet finalized, but I will continue tomorrow.
One thing I like to notice: In the current state I removed the magic, that looked around in the included file to find _some_ class that is not `abstract` and a subclass of `\PHPUnit\Framework\TestCase` if everything else fails. I could easily add this behavior again and was removing it because I think this should be part of this cleanup. Just ping me if you like to have that fallback added back again.

/Flo

**Comment by flow-control** [comment]
Rebased on `master` branch

**Comment by flow-control** [comment]
I'll have a look at the code coverage report. That decreased with rebasing on `master` branch :disappointed:

**Pull request merged**
