### PR TITLE
Fix: Use `PHPUnit\TestFixture` as namespace for test fixtures

### PR DESCRIPTION
**Pull request by localheinz**
This pull request

- [x] uses `PHPUnit\TestFixture` as namespace for test fixtures

### CODE REVIEW

**Comment by sebastianbergmann** [comment]
This branch has conflicts that must be resolved. Sorry :(

**Comment by localheinz** [comment]
@sebastianbergmann 

Rebased!

**Comment by localheinz** [comment]
Thank you, @sebastianbergmann!

Let me guess, conflicts?

😆

**Comment by sebastianbergmann** [comment]
Yes :(

**Comment by localheinz** [comment]
I will follow up, @sebastianbergmann!

**Pull request merged**
