### PR TITLE
Enhancement: Add PHP 8 to build matrix

### PR DESCRIPTION
**Pull request by localheinz**
This PR

* [x] adds PHP 8 to the build matrix

💁‍♂ For reference, see https://github.com/shivammathur/setup-php/issues/104.

### CODE REVIEW

**Comment by sebastianbergmann** [comment]
The `8` job uses `PHP 7.3.12`:

* https://github.com/sebastianbergmann/phpunit/pull/3979/checks?check_run_id=339672157#step:3:12
* https://github.com/sebastianbergmann/phpunit/pull/3979/checks?check_run_id=339672157#step:8:6

**Comment by shivammathur** [comment]
@sebastianbergmann @localheinz 
Please quote these versions as GitHub Actions truncates zeros after decimal in inputs.
```yml
php-version:
  - '7.3'
  - '7.4'
  - '8.0'
```

**Comment by localheinz** [comment]
Thank you, @shivammathur!

**Comment by shivammathur** [comment]
@localheinz
Please note that `Xdebug` currently does not support this version.

**Comment by localheinz** [comment]
Thank you for clarifying, @shivammathur!

**Comment by localheinz** [comment]
Thank you, @sebastianbergmann!

**Pull request merged**
