### PR TITLE
add File and Directory constraints and assertions

### PR DESCRIPTION
**Pull request by abacaphiliac**
add Constraints:
- PHPUnit_Framework_Constraint_DirectoryExists
- PHPUnit_Framework_Constraint_IsReadable
- PHPUnit_Framework_Constraint_IsWritable

add Assertions:
- assertIsReadable
- assertNotIsReadable
- assertIsWritable
- assertNotIsWritable
- assertDirectoryExists
- assertDirectoryNotExists
- assertDirectoryIsReadable
- assertDirectoryNotIsReadable
- assertDirectoryIsWritable
- assertDirectoryNotIsWritable
- assertFileIsReadable
- assertFileNotIsReadable
- assertFileIsWritable
- assertFileNotIsWritable

added tests to completely cover the constraints, and tests to cover most of the assertions... however it will be difficult/impossible to completely test some of the assertions without using a virtual filesystem. how do you feel about my inclusion of `mikey179/vfsStream` or a similar package for this purpose?

### CODE REVIEW

**Comment by sebastianbergmann** [comment]
Thank you for your contribution.

I am considering merging this for PHPUnit 5.6. Can you please open a pull request for https://github.com/sebastianbergmann/phpunit-documentation that documents these new assertions?

**Comment by abacaphiliac** [comment]
@sebastianbergmann thanks for making projects that are so easy to build and in which to contribute : )

here are the new docs: https://github.com/sebastianbergmann/phpunit-documentation/pull/382

please let me know if i have missed anything, or if it looks out of sorts.

**Comment by puregold117** [comment]
@sebastianbergmann  Thanks for the efforts

**Comment by sebastianbergmann** [comment]
Merged manually, thanks.

**Pull request closed without merging**
