### PR TITLE
Expand PHPT support with code coverage and more section support

### PR DESCRIPTION
**Pull request by kabel**
- Adds support for code coverage from PHPT tests
- Allows for an enforced (large test) timeout for phpt tests
- Adds PHPT section support for `ENV`, `STDIN`, `ARGS`, `FILEEOF`, `FILE_EXTERNAL`, `EXPECT_EXTERNAL`, `EXPECTF_EXTERNAL`, `EXPECTREGEX_EXTERNAL`
- `XFAIL` section will mark the test as incomplete
- An exception will be thrown if known unsupported sections are found

### CODE REVIEW

**Comment by sebastianbergmann** [comment]
Thank you working on this, Kevin. It looks good at first glance but I will have to review all the changes before merging.

**Comment by sebastianbergmann** [comment]
Can you please have a look at this test, Kevin?

```
There was 1 incomplete test:

1) /usr/local/src/phpunit/tests/TextUI/phpt-xfail.phpt
Syntax Error in PHPT is supposed to fail

/usr/local/src/phpunit/src/Extensions/PhptTestCase.php:208
/usr/local/src/phpunit/src/Framework/TestSuite.php:753
/usr/local/src/phpunit/src/Framework/TestSuite.php:753
/usr/local/src/phpunit/src/TextUI/TestRunner.php:457
/usr/local/src/phpunit/src/TextUI/Command.php:161
/usr/local/src/phpunit/src/TextUI/Command.php:112

Caused by
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'Should not see this'
+'Parse error: syntax error, unexpected '}' in - on line 2'

/usr/local/src/phpunit/src/Framework/Constraint/IsEqual.php:137
/usr/local/src/phpunit/src/Framework/Assert.php:1980
/usr/local/src/phpunit/src/Framework/Assert.php:513
/usr/local/src/phpunit/src/Extensions/PhptTestCase.php:116
/usr/local/src/phpunit/src/Extensions/PhptTestCase.php:205
/usr/local/src/phpunit/src/Framework/TestSuite.php:753
/usr/local/src/phpunit/src/Framework/TestSuite.php:753
/usr/local/src/phpunit/src/TextUI/TestRunner.php:457
/usr/local/src/phpunit/src/TextUI/Command.php:161
/usr/local/src/phpunit/src/TextUI/Command.php:112
```

**Comment by sebastianbergmann** [comment]
Nevermind, Kevin, I took care of that test locally.

**Comment by kabel** [comment]
Great. Thanks. I was wondering how best to handle the xfail test case, but didn't revisit it.

**Pull request merged**
