### PR TITLE
Catch and display errors during bootstrapping when using testdox printer

### LINKED ISSUE #3107: CliTestDoxPrinter::addError() cannot handle errors in setUpBeforeClass()
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 7.1.2
| PHP version         | 7.2.2
| Installation Method | PHAR

If you made error in TestCase, like calling non_existing_function(), you get error, which tells you nothing. In this case, I'm not able to find, that problem is non_existing_function().

class CombiPneuTestSnazzyBee extends PHPUnit\Framework\TestCase {
	
	public static function setUpBeforeClass() {
		non_existing_function();
	}
}

Produce:
PHP Fatal error:  Uncaught Error: Call to a member function fail() on null in phar://REAL_PATH/phpunit.phar/phpunit/Util/TestDox/CliTestDoxPrinter.php:116
Stack trace:
#0 phar://REAL_PATH/phpunit.phar/phpunit/Framework/TestResult.php(265): PHPUnit\Util\TestDox\CliTestDoxPrinter->addError(Object(PHPUnit\Framework\TestSuite), Object(PHPUnit\Framework\ExceptionWrapper), 0)
#1 phar://REAL_PATH/phpunit.phar/phpunit/Framework/TestSuite.php(754): PHPUnit\Framework\TestResult->addError(Object(PHPUnit\Framework\TestSuite), Object(PHPUnit\Framework\ExceptionWrapper), 0)
#2 phar://REAL_PATH/phpunit.phar/phpunit/TextUI/TestRunner.php(529): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#3 phar://REAL_PATH/phpunit.phar/phpunit/TextUI/Command.php(198): PHPUnit\TextUI\TestRunner->doRun(Object(PHPUnit\Framework\TestSuite), Array, true)
#4 phar://REAL_PATH/phpunit.phar/phpunit/TextUI/Command.php( in phar://REAL_PATH/phpunit.phar/phpunit/Util/TestDox/CliTestDoxPrinter.php on line 116

Fatal error: Uncaught Error: Call to a member function fail() on null in phar://REAL_PATH/phpunit.phar/phpunit/Util/TestDox/CliTestDoxPrinter.php:116
Stack trace:
#0 phar://REAL_PATH/phpunit.phar/phpunit/Framework/TestResult.php(265): PHPUnit\Util\TestDox\CliTestDoxPrinter->addError(Object(PHPUnit\Framework\TestSuite), Object(PHPUnit\Framework\ExceptionWrapper), 0)
#1 phar://REAL_PATH/phpunit.phar/phpunit/Framework/TestSuite.php(754): PHPUnit\Framework\TestResult->addError(Object(PHPUnit\Framework\TestSuite), Object(PHPUnit\Framework\ExceptionWrapper), 0)
#2 phar://REAL_PATH/phpunit.phar/phpunit/TextUI/TestRunner.php(529): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#3 phar://REAL_PATH/phpunit.phar/phpunit/TextUI/Command.php(198): PHPUnit\TextUI\TestRunner->doRun(Object(PHPUnit\Framework\TestSuite), Array, true)
#4 phar://REAL_PATH/phpunit.phar/phpunit/TextUI/Command.php( in phar://REAL_PATH/phpunit.phar/phpunit/Util/TestDox/CliTestDoxPrinter.php on line 116

### PR DESCRIPTION
**Pull request by rpkamp**
Fixes #3107 

It changes quite some stuff around, not sure if you're fine with breaking BC for this. If not, we'd need to find a different solution.

Example output:

screenshot from 2018-04-28 17-52-54

### CODE REVIEW

**Comment by sebastianbergmann** [comment]
Thank you for working on this!

Can you elaborate on the BC break?

[The tests fail on PHP 7.3.](https://travis-ci.org/sebastianbergmann/phpunit/jobs/372448332)

**Comment by sebastianbergmann** [comment]
@mhujer [PHPStan complains about a function that does not exist](https://travis-ci.org/sebastianbergmann/phpunit/jobs/372448334). That is, of course, correct but not what we want here.

**Comment by mhujer** [comment]
@sebastianbergmann It should be enough to add it to `ignoreErrors` section in [phpstan-tests.neon](https://github.com/sebastianbergmann/phpunit/blob/master/phpstan-tests.neon):

```
        # intentionally non existent function in tests/Regression/GitHub/3107/Issue3107Test.php
        - '#Function does_not_exist not found#'
```

(should be copy&paste-able)

**Comment by rpkamp** [comment]
Checking again I don't think there is a BC break after all, since the class that changed the most (now `PHPUnit\Util\TestDox\RunningTestResult`, used to be `PHPUnit\Util\TestDox\TestResult` - which is now an interface) was final anyway. so no-one could have extended that. They might have been using it, but that seems like a stretch.

**Comment by rpkamp** [comment]
- Fixed PHPStan error by adding it to `ignoreErrors` - thanks @mhujer 
- Fixed tests in PHP 7.3 by looking for %Sdoes_not_exist() in EXPECTF test
- Fixed CS errors

Commit amended and force pushed, all tests are green now

ping @sebastianbergmann

**Comment by sebastianbergmann** [comment]
Merged manually, thanks.

**Pull request closed without merging**
