### PR TITLE
TestCase->setExpectedException - properly handle lack of message

### PR DESCRIPTION
**Pull request by keradus**
ref https://github.com/sebastianbergmann/phpunit/commit/567ca23a4c62e8b9bcefae0b39b5f33e3853c2c2#commitcomment-24975103

### CODE REVIEW

**Comment by keradus** [comment]
@sebastianbergmann please mark `Skip branches without appveyor.yml` in AppVeyor config

**Comment by sebastianbergmann** [comment]
@keradus Done.

**Comment by sebastianbergmann** [comment]
Merged manually, thanks.

**Comment by keradus** [comment]
shall I add it to changelog https://github.com/sebastianbergmann/phpunit/commit/78532d5269d984660080d8e0f4c99c5c2ea65ffe ?

**Pull request closed without merging**
