### PR TITLE
revert #3891

### PR DESCRIPTION
**Pull request by realFlowControl**
Hey @sebastianbergmann,

as you stated in your [comment](https://github.com/sebastianbergmann/phpunit/issues/3889#issuecomment-540493309) in #3889, here is the PR to revert #3891 

This is related to #3859
/Flo

### CODE REVIEW

**Comment by mfn** [comment]
I commented already on https://github.com/sebastianbergmann/phpunit/pull/3891#issuecomment-542286009 but now that I see this change is reverted…

… it will break the PhpStorm phpunit integration for vagrant machine in some cases ( https://youtrack.jetbrains.com/issue/WI-49132 ) 

The command executed by PS looks something like this:
`/usr/bin/php /vagrant/project/vendor/phpunit/phpunit/phpunit --configuration /vagrant/project/phpunit.xml.dist --filter "/(::testAllFieldsWithPostContext)( .*)?$/" Project\\Api\\V2\\Tests\\GraphQL\\Queries\\ActivityLogConfigurationQuery\\ActivityLogConfigurationQueryTest /vagrant/project/tests/GraphQL/Queries/ActivityLogConfigurationQuery/ActivityLogConfigurationQueryTest.php --teamcity`

Strangely it works when executed manually but not when ran within PS

**Comment by sebastianbergmann** [comment]
@flow-control Can you have a look at the test failures?

**Comment by sebastianbergmann** [comment]
@mfn If this breaks PhpStorm (and we actually merge this) then PhpStorm needs to be updated for PHPUnit 9.

**Comment by flow-control** [comment]
@sebastianbergmann as we reverted everything, this is not needed anymore

**Pull request closed without merging**
