### PR TITLE
Closes #1802

### LINKED ISSUE #1802: Introduce separate class for warnings
## Example

```php
<?php
class Test extends PHPUnit_Framework_TestCase
{
}
```

## Actual

```
$ phpunit Test                                  
PHPUnit 5.0-g6caa139 by Sebastian Bergmann and contributors.

F

Time: 58 ms, Memory: 4.50Mb

There was 1 failure:

1) Warning
No tests found in class "Test".

FAILURES!
Tests: 1, Assertions: 0, Failures: 1.
```

## Expected

```
$ phpunit Test                                  
PHPUnit 5.0-g6caa139 by Sebastian Bergmann and contributors.

W

Time: 58 ms, Memory: 4.50Mb

There was 1 warning:

1) No tests found in class "Test".

WARNINGS!
Tests: 1, Assertions: 0, Warnings: 1.
```

### PR DESCRIPTION
**Pull request by Shaked**
Opened this pull request here as a request from @sebastianbergmann. For more information see https://github.com/sebastianbergmann/phpunit/pull/1838.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Looks pretty good to me. :+1:

**Comment by sebastianbergmann** [comment]
Merged manually, thanks.

**Comment by keradus** [comment]
Extending the `TestListener` interface on 5.1 (MINOR) update have broke the interface :(:(:(

**Comment by GrahamCampbell** [comment]
Not the only breaking change on 5.1 either. :(

**Comment by sebastianbergmann** [comment]
You are right, @keradus, and that should not have happened. However, test listeners should **extend** `BaseTestListener` instead of **implementing** `TestListener` directly.

**Comment by sebastianbergmann** [comment]
@GrahamCampbell Huh?

**Comment by GrahamCampbell** [comment]
The changing the call order for the before annotations stuff has broken thousands of Laravel applications.

**Comment by GrahamCampbell** [comment]
> Two months of beta and nobody reported any breaking change.

That;s because we're all rolling with a stable version. ;)

**Comment by keradus** [comment]
@sebastianbergmann but since the interface is public, it is still OK to implement it too, isn't it? And a lot of libraries used to typehint the interface, so it is a problem of BC breaker without MAJOR update. I know how to change the code to be able to run with changed interface, but it is better to fix it in the source library than in all external usages.

Any chances to get 5.x line fixed ?

**Comment by sebastianbergmann** [comment]
@keradus I am working on a fix.

**Comment by keradus** [comment]
Great to hear that! Thank you!

**Comment by sebastianbergmann** [comment]
I just released PHPUnit 5.1.1 which has 073c4de6d013353df368ccb25f9de37f13f61d2d. Thank you for bringing this to my attention!

**Comment by beberlei** [comment]
@GrahamCampbell the execution order of decoupled event listeners is *not* something you can rely on when its undefined. If this break testing in Laravel core, then this must be because there is high temporal coupling, where there shouldn't be. This means its a bug in Laravel.

**Comment by GrahamCampbell** [comment]
> @GrahamCampbell the execution order of decoupled event listeners is not something you can rely on when its undefined.

But we're NOT relying on that. Only that the setup method is run first. I don't care what order the before methods are run, so long as it's after the setup method.

**Comment by beberlei** [comment]
@GrahamCampbell but the order of setup or annotations first was undefined as well, PHPUnit never guaranteed that one runs before the other. If you rely on it, then you rely on undefined behavior and that can change without being a BC break.

**Comment by GrahamCampbell** [comment]
Then it shouldn't matter to you if this is reverted by the same argument...

**Pull request closed without merging**
