### PR TITLE
Travis - List packages installed by installed

### PR DESCRIPTION
**Pull request by SpacePossum**
This makes development more easy.

### CODE REVIEW

**Comment by sebastianbergmann** [comment]
Can you elaborate why this makes development easier?

**Comment by SpacePossum** [comment]
Sure :)
Typically a well disciplined developer will run your PHPUnit before making a PR, this to make sure it should be a good contribution. However, this is usually done limited to one PHP version on one OS and with one set of packages installed by composer.
The Travis configuration of this repo tests with two versions of the required packages, the latest stable version of those packages and the lowest stable (which is a very nice thing btw :)), both on Linux.
So when Travis fails the bug hunt begins. 
So lets say the PHP version and OS have been singled out as possible cause of the failure, then the failure might be related to different packages used during testing by Travis than used by the developer.
Having the information at hand of which packages were used by Travis the developer can easily get the exact same packages and test locally. Not having that information means the developer has to test all kinds of combinations which might have been used by Travis in order to reproduce the failure.
This can be time consuming and given that displaying the versions of the packages used by Travis is fairly cheap I think it is a good thing to add.

**Comment by sebastianbergmann** [comment]
I did not see `composer info -D | sort` in the "noise" of the pull request, my bad.

However, I think that `composer info -D | sort` superfluous. The information is already present in the output of `composer update`:
```
$ if [[ "$DEPENDENCIES" = 'high' ]]; then travis_retry composer update --no-interaction --no-ansi --no-progress --no-suggest --optimize-autoloader --prefer-stable; fi
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 27 installs, 0 updates, 0 removals
  - Installing phar-io/version (1.0.1): Downloading (100%)
  - Installing phar-io/manifest (1.0.1): Downloading (100%)
  - Installing sebastian/recursion-context (3.0.0): Downloading (100%)
  - Installing doctrine/instantiator (1.0.5): Downloading (100%)
  - Installing sebastian/exporter (3.1.0): Downloading (100%)
  - Installing sebastian/diff (1.4.3): Downloading (100%)
  - Installing sebastian/comparator (2.0.0): Downloading (100%)
  - Installing webmozart/assert (1.2.0): Downloading (100%)
  - Installing phpdocumentor/reflection-common (1.0): Downloading (100%)
  - Installing phpdocumentor/type-resolver (0.4.0): Downloading (100%)
  - Installing phpdocumentor/reflection-docblock (3.2.0): Downloading (100%)
  - Installing phpspec/prophecy (v1.7.0): Downloading (100%)
  - Installing sebastian/object-reflector (1.1.1): Downloading (100%)
  - Installing sebastian/object-enumerator (3.0.2): Downloading (100%)
  - Installing sebastian/resource-operations (1.0.0): Downloading (100%)
  - Installing theseer/tokenizer (1.1.0): Downloading (100%)
  - Installing sebastian/version (2.0.1): Downloading (100%)
  - Installing sebastian/environment (3.1.0): Downloading (100%)
  - Installing sebastian/code-unit-reverse-lookup (1.0.1): Downloading (100%)
  - Installing phpunit/php-token-stream (1.4.11): Downloading (100%)
  - Installing phpunit/php-text-template (1.2.1): Downloading (100%)
  - Installing phpunit/php-file-iterator (1.4.2): Downloading (100%)
  - Installing phpunit/php-code-coverage (5.2.1): Downloading (100%)
  - Installing myclabs/deep-copy (1.6.1): Downloading (100%)
  - Installing phpunit/php-timer (1.0.9): Downloading (100%)
  - Installing phpunit/phpunit-mock-objects (4.0.2): Downloading (100%)
  - Installing sebastian/global-state (2.0.0): Downloading (100%)
Writing lock file
Generating optimized autoload files
```
Or am I missing something?

**Comment by sebastianbergmann** [comment]
With the exception of `git: depth: 1` (the checkout currently takes ~ 1 second on Travis, I don't see the point trying to improve that) and `composer info -D | sort` (see above) I have adopted all the changes proposed in this pull request.

**Pull request closed without merging**
