### PR TITLE
Improve Util\Exporter::export() tests

### PR DESCRIPTION
**Pull request by mvorisek**
improve #5599 tests and add tests for #5624 ~and #5625~

### CODE REVIEW

**Comment by mvorisek** [comment]
E2E tests are failing on Windows, how to fix that?

**Comment by sebastianbergmann** [comment]
Thank you for your contribution. I appreciate the time you invested in preparing this pull request. However, this is not actionable for me as it implements three (at least to me) three separate changes from two commits in one pull request.

**Comment by mvorisek** [comment]
@sebastianbergmann I have opened 2 separate PRs with the actual fixes. I would be happy if you can reopen this PR so I can rework it to contain only the tests.

**Comment by sebastianbergmann** [comment]
Merged manually, thanks.

**Comment by sebastianbergmann** [comment]
*sigh*

After merging this, one of the tests now fails on Windows: https://github.com/sebastianbergmann/phpunit/actions/runs/7346030691/job/20000143074

@mvorisek Any idea what might be going on here? Thanks!

**Comment by mvorisek** [comment]
@sebastianbergmann see PR description ;-) - you requested the fixes in separate PRs

**Pull request closed without merging**
