### PR TITLE
Use short array syntax on "phpunit" file

### PR DESCRIPTION
**Pull request by henriquemoody**
Just a tip, I don't know if you know that:

When the pull request is up to date with the target branch and you reset the target branch to the pull request, the pull request is marked as merged automatically. Like:

```
(master) $ git reset --hard origin/pr/1842
(master) $ git push origin master
```

That's because GitHub recognizes the hash of the commit on the target branch.

I'm doing that on my projects. Sometimes the pull requests are not up to date, them I just cherry-pick the commits or, after do what I commented above, I rebase it with remote target branch, like:

```
(master) $ git rebase origin/master
```

Then I push it again.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
:-1:

**Comment by GrahamCampbell** [comment]
This breaks the file on php 5.3 so we can't display the error message that 5.6 is needed.

**Comment by GrahamCampbell** [comment]
Something simelar came up in composer where by php 5.2 was broken.

**Comment by henriquemoody** [comment]
Hum... I see, you're right. I'm closing this pull request, so.

**Pull request closed without merging**
