### PR TITLE
Exclude internal tests from composer dist packages

### PR DESCRIPTION
**Pull request by Tobion**
See discussion for example https://github.com/symfony/symfony/pull/33579

It was already done in phpunit in https://github.com/sebastianbergmann/phpunit/commit/d99e588e3cbab28db86f8da22e22c72d8cc38543 but reverted because it also removed the changelog and license file by mistake.

### CODE REVIEW

**Comment by sebastianbergmann** [comment]
Thank you for your contribution. I appreciate the time you invested in preparing this pull request. However, I have decided not to merge it.

**Comment by simonschaufi** [comment]
@sebastianbergmann could you explain why you left out `/tests export-ignore`? Nobody needs the internal tests of phpunit. I also found this interesting comment: https://github.com/Codeception/Codeception/pull/5527#issue-282555074 and this one: https://www.emergeinteractive.com/insights/detail/does-irresponsible-web-development-contribute-to-global-warming/ Save the :earth_africa: and reduce global warming!

**Comment by sebastianbergmann** [comment]
AFAIK, @remicollet and other downstream packagers rely on tests etc. being included in release tarballs. I would gladly add them to `export-ignore` if that were not the case.

**Comment by Tobion** [comment]
They can still have the tests by using prefer-source. That's not a valid argument to not change it.

**Comment by sebastianbergmann** [comment]
I think you are right. And I think that `prefer-source` may not have existed when @remicollet asked me to not exclude tests. I will go through my repositories and make the necessary changes.

**Comment by remicollet** [comment]
This has been discussed ad-nauseam.

"prefer-source' is a composer option, so only for composer user.

tests are part of the project so have to be part of the public tarball, like documentation, license, or any other file used by the project.

Again THIS IS A COMPOSER ISSUE, not being able to manage file "roles"

PHP is the only language in the world to NOT have any INSTALLER (and composer is not an installer, only a dependency manager).

perl have cpan,
python have pip
nodejs have npm
...

Even the old PEAR was able to manage file "roles"

BTW, using git snapshot instead of official tarball still possible

This issue make all non-php developers laugh, so continue, in our strange configned world, always nice to have something to laugh about.

**Comment by simonschaufi** [comment]
@remicollet what is the difference between npm and composer? For me they do the same.

**Comment by remicollet** [comment]
"npm install foo" is able to install only needed scripts, without using any .gitattributes hack.

**Pull request closed without merging**
