### PR TITLE
Enhancement: Configure binary_operator_spaces fixer

### PR DESCRIPTION
**Pull request by localheinz**
This PR

* [x] configures the `binary_operator_spaces` fixer
* [x] runs `php-cs-fixer fix`

Slightly related to #4311.

### CODE REVIEW

**Comment by localheinz** [comment]
@sebastianbergmann 

In case you like this, shall I target a different branch?

**Comment by sebastianbergmann** [comment]
I like this -- a lot. Thanks! Please send it against `8.5` and I'll take care from there.

**Comment by epdenouden** [comment]
oooh nice

**Review by epdenouden — APPROVED** [review]
much cleaner!

**Comment by localheinz** [comment]
Thank you, @epdenouden and @sebastianbergmann!

**Pull request merged**
