### PR TITLE
British English: colour

### PR DESCRIPTION
**Pull request by franzholz**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
This is confusing now having the flag in American english, but the description in British.

**Comment by franzholz** [comment]
Should the flag option also be changed from 'color' into 'colour'?

**Comment by GrahamCampbell** [comment]
We can't do that in 4.x.

**Comment by whatthejeff** [comment]
I really don't see the value in changing a command line option that's been around since 2008. Seems a bit excessive considering most people likely understand the meaning regardless of the regional spelling.

**Comment by franzholz** [comment]
Maybe it is a solution to silently (undocumented) keep the American writing as well.

**Comment by whatthejeff** [comment]
I discussed this with @sebastianbergmann on gitter. We decided to stick with the current spelling since American English is more ubiquitous in the PHP world.

**Pull request closed without merging**
