### PR TITLE
Support to pass an expected exception to a callback for validation

### PR DESCRIPTION
**Pull request by UlrichEckhardt**
Heya!

I found https://github.com/sebastianbergmann/phpunit/pull/1726 in my personal backlog, and rebased in onto the current master branch. Anyhow, so much for the background of this... ;)

### Rationale
In some cases I want to inspect more of the thrown exceptions than just the type, message and errorcode. Up to now, I have to do it manually:

```
try {
    $testee->run();
    $this->fail("expected exception not raised");
} catch (\MyException $e) {
    $this->assertEquals(MyException::CATEGORY_FATAL, $e->category());
}
```

There are a few downsides to this:
 * I need to check the failure to throw explicitly.
 * I should check for wrong exceptions. I don't it above, because it's just too much code.

### Solution
The pull request here adds another function to validate expected exceptions using a callback. It allows this kind of test instead:

```
$this->expectExceptionCallback(
    function (\MyException $e) {
        $this->assertEquals(MyException::CATEGORY_FATAL, $e->category());
    }
);
$testee->run();
```
This code allows you to
 * verify that the exception type matches.
 * verify that the exception is thrown.
 * write custom validation code for the exception type.

What do you think?

### CODE REVIEW

**Comment by UlrichEckhardt** [comment]
Just a note: I tried to fix the issues raised by the autotest. Some of them were pretty easy. However, I'd like some guidance on the remaining two:
 * Firstly, why does it report backward compatibility issues in multiple cases? Is that test relevant to my PR or can it be ignored?
 * Secondly, the type checker. It reports a wrong parameter for the constructor of `ReflectionFunction`, but firstly it works and secondly it's also documented to work that way. Suggestions?

**Comment by sebastianbergmann** [comment]
Thank you for your contribution. I appreciate the time you invested in preparing this pull request. However, I have decided not to merge it as I believe the current means for expecting/verifying exceptions to be sufficient.

**Comment by UlrichEckhardt** [comment]
Can you elaborate a bit? Of course, this only provides syntactic sugar, but that is IMHO pretty much in line with many other interfaces (`assert...` functions, `Constraint`-generating factory functions).

**Comment by UlrichEckhardt** [comment]
Ping @sebastianbergmann?

On a related note, an even better approach might be to allow passing a `Constraint` to `expectException()`, to reuse existing infrastructure to specify a match.

**Comment by UlrichEckhardt** [comment]
Ping @sebastianbergmann?

**Comment by sebastianbergmann** [comment]
I have said all I have to say on this subject.

**Comment by UlrichEckhardt** [comment]
Okay, you kind-of made your position clear.

**Pull request closed without merging**
