### PR TITLE
Implement PHPUnit\Framework\TestCase::getCurrentProviderDataSet()

### PR DESCRIPTION
**Pull request by chaos0815**
Having access to the providers data, one can create mocks in the setUp() according to the given data.
Currently we only have access to the data in string form.

### CODE REVIEW

**Comment by brizzz** [comment]
:+1: need exactly that feature now

**Comment by sebastianbergmann** [comment]
Can you please provide a minimal, self-contained example of a test that uses this? Thanks!

**Comment by chaos0815** [comment]
```php
/**
 * Class DataSetTest
 */
class DataSetTest extends \PHPUnit_Framework_TestCase {
    private $mockObject;

    /**
     * setUp
     *
     * @return void
     */
    protected function setUp() {
        parent::setUp();

        $data = $this->getCurrentProviderDataSet();

        $this->mockObject = $this->getMockBuilder('SomeClass')->setMethods(['someMethod'])->getMock();
        $this->mockObject->method('someMethod')->willReturn($data[0]);
    }

    /**
     * testSets
     *
     * @param int $a a
     *
     * @dataProvider getData
     *
     * @return void
     */
    public function testSets($a) {
        $this->assertEquals($a, $this->mockObject->someMethod());
    }

    /**
     * getData
     *
     * @return array
     */
    public function getData() {
        return [
            [1],
            [3]
        ];
    }
}
```

**Comment by sebastianbergmann** [comment]
Thanks!

**Comment by sebastianbergmann** [comment]
Merged manually, thanks.

**Comment by sebastianbergmann** [comment]
Due to #2320, `PHPUnit_Framework_TestCase::getDataSet()` had to be renamed to `PHPUnit_Framework_TestCase::getProvidedData()`.

**Pull request closed without merging**
