### PR TITLE
Fix: Avoid use of empty()

### PR DESCRIPTION
**Pull request by localheinz**
This PR

* [x] avoids the use of `empty()` where possible

### CODE REVIEW

**Comment by sebastianbergmann** [comment]
Why do you want to avoid `empty()`?

**Comment by localheinz** [comment]
@sebastianbergmann 

Perhaps it is a matter of taste, but with `empty()`, I find that the author's intent is unclear.

```php
var_dump([
    'array' => empty([]),
    'bool-false' => empty(false),
    'float' => empty(0.0),
    'int' => empty(0),
    'null' => empty(null),
    'string' => empty(''),
    'undefined' => empty($foo),
]);
```

All of these evaluate to `true`.

By not using `empty()`, we can clarify the intent.

**Comment by epdenouden** [comment]
I like empty() more because that want to express, but I also like [] as it's more precise.

Yes I'll go make myself useful somewhere else now.

**Comment by localheinz** [comment]
@epdenouden @sebastianbergmann 

Ha, no problem!

🤓

**Comment by epdenouden** [comment]
Well you didn't have to close it, is what I was saying. Even if you do, I will be using more specific conditionals where appropriate anyway. :)

I also get @sebastianbergmann: with increasingly type-strict code the meaning of empty()

Question @localheinz, is it possible to teach Psalm to complain about ambiguous use of empty and leave it alone when it can deduce the type?

**Comment by localheinz** [comment]
@epdenouden 

That’s probably a question @muglug can answer!

☺️

**Comment by sebastianbergmann** [comment]
Does Psalm "complain" about `empty()`?

**Comment by epdenouden** [comment]
Currently it doesn't. I don't mind either way :)

**Pull request closed without merging**
