### PR TITLE
Enhancement: Add job to assert that generated files are up-to-date

### PR DESCRIPTION
**Pull request by localheinz**
This PR

* [x] adds a job to assert that generated files are up-to-date

Related to #4418.

### CODE REVIEW

**Comment by sebastianbergmann** [comment]
We already have https://github.com/sebastianbergmann/phpunit/blob/master/tests/unit/Framework/Assert/FunctionsTest.php which *should* prevent the most common case that updating the generated file was forgotten when a new assertion method was added.

**Comment by sebastianbergmann** [comment]
I do not like the "Generate Code" name for the job. Yes, we generate code as part of that job. But that is not what the job is about. It is about whether the generated file is up-to-date or not. I do not have a better name just yet.

**Comment by localheinz** [comment]
@sebastianbergmann 

We could make this part of the **Tests** job - after all, it tests something. What do you think?

**Comment by sebastianbergmann** [comment]
> We could make this part of the **Tests** job - after all, it tests something. What do you think?

Makes sense to me.

**Comment by sebastianbergmann** [comment]
> > We could make this part of the **Tests** job - after all, it tests something. What do you think?
> 
> Makes sense to me.

Sorry for the noise, after a long time of silence no less, but I do think that if we do this then it should be a separate job. Let us call it "Test generated code"?

**Comment by localheinz** [comment]
@sebastianbergmann 

I have renamed the job, please take a look!

**Pull request merged**
