### PR TITLE
Make same and equals string messages the same

### LINKED ISSUE #2308: Better failure message when asserting that two strings are equal
This is a feature request but I'm not sure if it's about PHPUnit or PHPStorm IDE

When using `$this->assertSame()` with strings, you may get the following failure message:
image

It would be useful to have: 
- string length or quotes like with `var_dump` to spot a trailing space for instance
- var type in case the expected value is an empty string `''` and the actuel one is `false` or `null`

### PR DESCRIPTION
**Pull request by exussum12**
Fixes #2308

### CODE REVIEW

**Comment by exussum12** [comment]
The second part of this (showing the type) I think needs to be fixed here https://github.com/sebastianbergmann/comparator

**Comment by sebastianbergmann** [comment]
The breaks PHPUnit's own test suite. Can you please update the tests?

**Comment by exussum12** [comment]
It was already broken :( something about can't auto pad class ? I had to check out an older version of master  to test.

**Comment by sebastianbergmann** [comment]
Without your patch, all tests in `master` pass. Both locally on my machine as well as on Travis.

**Comment by exussum12** [comment]
Running ant fixed the issue, looking at the failures no

**Comment by exussum12** [comment]
Im going to close this PR and there is a fair bit of work to make the two consistent, Will reopen when that is done

**Pull request closed without merging**
