### PR TITLE
Use snapshot nodelist

### PR DESCRIPTION
**Pull request by theseer**

### CODE REVIEW

**Comment by sebastianbergmann** [comment]
Looks to me like a duplicate of #4420.

**Comment by theseer** [comment]
No, it had two additional changes that were unrelated to the previous issue. I branched of the Branch I used for #4419 though. That might have been a stupid idea but I wanted to ensure that the `SnapshotNodeList` is already present...

**Comment by sebastianbergmann** [comment]
I need this against (the current state of) `9.3` though. Sorry!

**Comment by theseer** [comment]
Actually, I'm not sure how to "fix" this PR ;)

**Comment by theseer** [comment]
I'll do a new one.

**Pull request closed without merging**
