### PR TITLE
Print duration of the tests events in the TeamCity logger

### PR DESCRIPTION
**Pull request by wbars**
fixes https://youtrack.jetbrains.com/issue/WI-36291 for PHPUnit >= 5.0

### CODE REVIEW

**Comment by sebastianbergmann** [comment]
I manually merged this into `7.3` and `master`.

If possible/applicable, please also send a pull request for `6.5`. Thanks!

**Comment by wbars** [comment]
@sebastianbergmann Sure, here it is #3252. Could you please give an insight in what PHPUnit releases these patches will be shipped so I can inform the users?

**Comment by sebastianbergmann** [comment]
PHPUnit 6.5.12 and PHPUnit 7.3.2 will have the fix. As bugfix releases do not follow a fixed schedule, I cannot give you a date. But it should be either this week or next week.

**Comment by wbars** [comment]
@sebastianbergmann Perfect, thanks!

**Pull request closed without merging**
