### PR TITLE
Allow to filter for multiple test suites

### PR DESCRIPTION
**Pull request by lcobucci**
This change allows users to run pass multiple test suites on the option `testsuite`.
e.g.: `--testsuite one,two`.

I didn't add any unit test since I couldn't find any test that uses the `$testSuiteFilter`, definitely you guys can help me to do it so.

### CODE REVIEW

**Comment by lcobucci** [comment]
@sebastianbergmann @whatthejeff I don't know if you had time to check this but this little patch is being really useful for us, what's your opinion?

**Comment by jmauerhan** [comment]
I would love this functionality. :D

**Comment by SelectiveAlso** [comment]
+1

**Comment by sebastianbergmann** [comment]
Merged manually, thanks.

**Comment by lcobucci** [comment]
@sebastianbergmann thanks!

**Pull request closed without merging**
