### PR TITLE
fix for missing loggerType coverage-xml in .xsd

### PR DESCRIPTION
**Pull request by thoys**
added missing loggerType coverage-xml to phpunit.xsd file

### CODE REVIEW

**Comment by thoys** [comment]
@sebastianbergmann this tag is also missing in https://schema.phpunit.de/4.5/phpunit.xsd  and all other schema's, can they be updated for backwards compatibility?

**Comment by sebastianbergmann** [comment]
Cherry-picked into `4.8` and merge from there to all newer branches. Thanks.

**Comment by thoys** [comment]
@sebastianbergmann, cool no problem, will it auto-publish to the https://schema.phpunit.de/4.8/phpunit.xsd later today?

**Comment by sebastianbergmann** [comment]
There is a nightly job that does that, yes.

**Comment by thoys** [comment]
Ty for the quick responses and handling. Good day

**Pull request closed without merging**
