### PR TITLE
TestDox colorization

### PR DESCRIPTION
**Pull request by epdenouden**
While working on the [buffered TestDox printer](https://github.com/sebastianbergmann/phpunit/pull/3417) I found the output format really useful for  work on the terminal. Adding some color highlighting and removing clutter gives it a completely different look. It's much easier to spot when something needs attention.

### Changes
Basic handling of ANSI colors gets its own helper class until we migrate over to a better CLI/console library. Its own test suite gives a quick demo of most features:

image

- mark changes in `TestSuite` by underlining the class name or class `@testdox`-annotation
- when verbose the test duration mirrors the status color
- reduced typographic clutter when using color
- `@dataprovider` parameter values used in `@testdox` are highlighted
- `@testdox` has access to the name of the `@dataprovider`-row via `$_dataName`
- show whitespace using dimmed interpuncts 
- improved visualization for support for `@dataprovider` without `@testdox`

image

- mirror test status colors in exception/error messages
- use dimmed colors to make PHPT path and filenames easier to read
- use dimmed colors to draw attention to changes in PHPT working directory
- highlighted stacktraces: changes in path+file, line numbers

image

The `CLITestDoxPrinter` has been cleaned up further. It has given me fresh ideas for the `TestListener` rewrite and cleaning up the pile of slow end-to-end tests. I'll be creating issues with proposed practical solutions for this. This has been a nice warming up for working on a new implementation for the test result event system.

Any remarks or ideas are very welcome as always.

### CODE REVIEW

**Comment by sebastianbergmann** [comment]
Wow! :-)

**Comment by sebastianbergmann** [comment]
Please change the target from `7.5` to `master` (`7.5.0` was released today). Thanks!

**Comment by epdenouden** [comment]
No problem, will rebase on `master` when I'm done with the finishing touches. :)

**Comment by epdenouden** [comment]
@sebastianbergmann I have rebased it on `master` and all looks fine. If you are happy with it you can merge it, the ongoing small improvements can go in a future pull request together with other small housekeeping.

**Comment by epdenouden** [comment]
🎄 🎁 

@sebastianbergmann  I'm going to continue my test suite related housekeeping on #3453 before this pull gets too big.

**Comment by sebastianbergmann** [comment]
Is this ready to be merged or should it wait for #3453?

**Comment by epdenouden** [comment]
It's ready to be merged. I have only been adding little improvements, while keeping everything stable. :-)

Still have some ideas like colorized help and ```--list*``` options. I will make those seperate pull requests when done.

**Comment by rpkamp** [comment]
This looks awesome, @epdenouden! Nice work :slightly_smiling_face:

**Comment by epdenouden** [comment]
@rpkamp Thanks! It is nice to hear people enjoy using the stuff I enjoy making. 🍰 If you have any wishes or ideas let me know, I do intend to keep improving the various output formats incrementally.

**Pull request merged**
