### PR TITLE
willThrowException() only accepts Exception, not Throwable

### PR DESCRIPTION
**Pull request by Stadly**

### CODE REVIEW

**Comment by gmponos** [comment]
I need this too.. any progress?

**Comment by epdenouden** [comment]
Change looks useful. @stadly can you merge in the latest master, so all tests run? Thx

**Comment by Stadly** [comment]
Done

**Comment by epdenouden** [comment]
That's quick, thank you!

**Comment by epdenouden** [comment]
@sebastianbergmann Change looks useful to me, would be nice to merge this, unless you know of something else breaking. The logging and reporting side uses `Throwable` already, too.

**Comment by gmponos** [comment]
@epdenouden I am not sure if with the current change other places must change as well...

I mean what about `expectedException` function.. this must also allow `Throwables`.. 

Haven't checked the code though... so it might already be fine...

**Comment by gmponos** [comment]
> The logging and reporting side uses Throwable already, too

@epdenouden ah.. when you were saying reporting you were referring to things like `expectedException`?

**Comment by epdenouden** [comment]
@gmponos That is a good point. I have not done an in-depth code review of the surrounding code. 🤐 Internally I think we can upgrade it all to `Throwable` anyway. Only exception would be strict checks for `Exception`, I think.

With the reporting I only meant the method signatures in the printers and listeners. Lots of stuff going to be refactored there and `Throwable` is the new fashionable thing. :)

**Comment by gmponos** [comment]
On the other hand you could accept current PR and see the other places later.. your call..

**Comment by epdenouden** [comment]
Yes. The built-in collection of tests should keep us relatively safe 😂

**Comment by sebastianbergmann** [comment]
Merged manually, thanks.

**Pull request closed without merging**
