### PR TITLE
Fix insulated tests with phpdbg

### LINKED ISSUE #1955: @runTestsInSeparateProcesses fails when running tests with phpdbg -qrr
Running tests in a separate process does not work when run with the `phpdbg -qrr phpunit`

### PR DESCRIPTION
**Pull request by nicolas-grekas**
Fixes #1955

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Nice fix. :+1:

**Comment by sebastianbergmann** [comment]
Thanks. I do think, though, that this should go into the `Runtime` class. Or?

**Comment by nicolas-grekas** [comment]
It could but it's not trivial: -d options needs to be before the eval-stdin.php on the command line, which means that simple concatenation doesn't work...

**Comment by sebastianbergmann** [comment]
Okay. Sounds like one more reason to work on #1342 then.

**Comment by bwoebi** [comment]
This, … well https://bugs.php.net/73484

This doesn't fix the bug, it just ends up not running the tests at all due to the use of php://input instead of php://stdin.

**Comment by sebastianbergmann** [comment]
Pull requests welcome! :-)

Truth be told, neither process isolation nor PHPDBG compatibility are high priority topics for me.

**Comment by bwoebi** [comment]
Yeah, see #2356 ;-)

**Pull request merged**
