### PR TITLE
Ensure environment values are stored in $_ENV

### PR DESCRIPTION
**Pull request by IchHabRecht**
in \PHPUnit\Util\Configuration

### CODE REVIEW

**Comment by sebastianbergmann** [comment]
Looks like a bugfix that should go at least into `7.2`. Does it also need to go into `6.5`?

**Comment by IchHabRecht** [comment]
@sebastianbergmann 
I would love to have it in both versions, yes. I didn't found any information in your contribution workflow how to deal with the branches/versions. Do you need pull requests for each branch instead of the one against master?

**Comment by sebastianbergmann** [comment]
One pull request is enough. If it's for a bugfix then it should be made against the oldest branch still supported, which is `6.5` at this point in time.

**Comment by IchHabRecht** [comment]
Thank you for the fast merge!

**Comment by sebastianbergmann** [comment]
Thank you for the pull request :)

**Pull request merged**
