### PR TITLE
Fixed #2431 - ArrayAccess support missing in assertArraySubset

### LINKED ISSUE #2431: assertArraySubset doesn't support ArrayAccess although it's documented
So I [dug into the code](https://github.com/sebastianbergmann/phpunit/blob/5.7/src/Framework/Assert.php#L63) and it looks like someone forgot to update this method when they added `ArrayAccess` support to `assertArrayHasKey` & `assertArrayNotHasKey`

### PR DESCRIPTION
**Pull request by exts**
Fixes #2431 - Added `ArrayAccess` support to assertArraySubset

### CODE REVIEW

**Comment by exts** [comment]
Looks like you can close #2108 as well.

**Comment by sebastianbergmann** [comment]
Merged manually, thanks.

**Comment by nisevi** [comment]
hi there, @sebastianbergmann @exts I think that maybe the fix is not working properly.

I'm trying to test this structure:

```
 13     public function testMethodAll()                                                                                                                                                                            
 14     {                                                                                                                                                                                                          
 15         factory(Role::class, 'superadmin')->create();                                                                                                                                                          
 16         $response = $this->call('GET', '/');                                                                                                                                                                   
 17         $this->get('api/v1/roles')                                                                                                                                                                             
 18             ->seeJsonStructure(                                                                                                                                                                                
 19                 [                                                                                                                                                                                              
 20                     'total',                                                                                                                                                                                   
 21                     'per_page',                                                                                                                                                                                
 22                     'current_page',                                                                                                                                                                            
 23                     'last_page',                                                                                                                                                                               
 24                     'next_page_url',                                                                                                                                                                           
 25                     'prev_page_url',                                                                                                                                                                           
 26                     'from',                                                                                                                                                                                    
 27                     'to',                                                                                                                                                                                      
 28                     'data' => [                                                                                                                                                                                
 29                         '*' => [                                                                                                                                                                               
 30                             'id',                                                                                                                                                                              
 31                             'name',                                                                                                                                                                            
 32                             'description',                                                                                                                                                                     
 33                             'created_at',                                                                                                                                                                      
 34                             'updated_at'                                                                                                                                                                       
 35                         ],                                                                                                                                                                                     
 36                         'limit'                                                                                                                                                                                
 37                     ]                                                                                                                                                                                          
 38                 ]                                                                                                                                                                                              
 39             );                                                                                                                                                                                                 
 40     }
```

and if I write one of the keys wrong on purpose, then the test will fails as it should, eg.:
```
$ phpunit --filter RoleControllerTest
PHPUnit 5.7.5 by Sebastian Bergmann and contributors.

F...                                                                4 / 4 (100%)

Time: 2.02 seconds, Memory: 24.00MB

There was 1 failure:

1) RoleControllerTest::testMethodAll
Failed asserting that an array has the key 'descriptio'.

/home/nisevi/documents/recom-electronics/keepclear-backend/vendor/laravel/framework/src/Illuminate/Foundation/Testing/Concerns/MakesHttpRequests.php:369
/home/nisevi/documents/recom-electronics/keepclear-backend/vendor/laravel/framework/src/Illuminate/Foundation/Testing/Concerns/MakesHttpRequests.php:363
/home/nisevi/documents/recom-electronics/keepclear-backend/vendor/laravel/framework/src/Illuminate/Foundation/Testing/Concerns/MakesHttpRequests.php:367
/home/nisevi/documents/recom-electronics/keepclear-backend/tests/api/RoleControllerTest.php:20

FAILURES!
Tests: 4, Assertions: 22, Failures: 1.
``` 

but if everything is ok I get:
```
$ phpunit --filter RoleControllerTest
PHPUnit 5.7.5 by Sebastian Bergmann and contributors.

E...                                                                4 / 4 (100%)

Time: 2.02 seconds, Memory: 24.00MB

There was 1 error:

1) RoleControllerTest::testMethodAll
PHPUnit_Framework_Exception: Argument #2 (No Value) of PHPUnit_Framework_Assert::assertArrayHasKey() must be a array or ArrayAccess

/home/nisevi/documents/recom-electronics/keepclear-backend/vendor/laravel/framework/src/Illuminate/Foundation/Testing/Concerns/MakesHttpRequests.php:369
/home/nisevi/documents/recom-electronics/keepclear-backend/vendor/laravel/framework/src/Illuminate/Foundation/Testing/Concerns/MakesHttpRequests.php:363
/home/nisevi/documents/recom-electronics/keepclear-backend/vendor/laravel/framework/src/Illuminate/Foundation/Testing/Concerns/MakesHttpRequests.php:367
/home/nisevi/documents/recom-electronics/keepclear-backend/tests/api/RoleControllerTest.php:20

ERRORS!
Tests: 4, Assertions: 24, Errors: 1.
```

Do you think that is has to be with this fix?

**Comment by exts** [comment]
@nisevi looking at your error in the last message: This issue fixes a specific issue which gives support for `ArrayAccess` in `assertArraySubset()`

Your error has to do with laravel passing an empty value to the `assertArrayHasKey()` which is a completely different function.

After doing some digging, create an issue over on the laravel github with your issue and refer to [this](https://github.com/laravel/framework/blob/5.4/src/Illuminate/Foundation/Testing/TestResponse.php#L28) block of code

**Comment by nisevi** [comment]
Hey @exts sorry I deleted my comment since I thought I was doing something wrong, and I didn't want to bother. Cool I will create an issue on the Laravel repository.

Thank you.

**Pull request closed without merging**
