### PR TITLE
Fix for assertCount expected size for Generator

### PR DESCRIPTION
**Pull request by kubawerlos**
https://github.com/sebastianbergmann/phpunit/issues/3302

### CODE REVIEW

**Comment by sebastianbergmann** [comment]
This does not solve the underlying problem that `assertCount()` modifies the generator.

**Comment by kubawerlos** [comment]
I don't know if it is possible in PHP.

> the only sensible thing to do here would be to disallow `assertCount()` on generators.

Should we follow this path? If so, target it to `master` as BC break or to `7.3` as bugfix?

**Review by JeroenDeDauw — APPROVED** [review]

**Comment by JeroenDeDauw** [comment]
@sebastianbergmann I don't see why that would be a problem. Going through a generator always does this in PHP, so it is expected behavior. Disallow it in assertCount would just force people to create such assertions themselves, which seems like loss-loss to me.

**Comment by epdenouden** [comment]
From a developer perspective: whatever the underlying language feature does internally, I would expect an `assertCount` to work as the name suggests and not give me "size 0" errors.

**Review by guilliamxavier — CHANGES_REQUESTED** [review]
Please consider:

```php
$gen2 = function () { yield 1; yield 2; };
$gen3 = function () { yield 1; yield 2; yield 3; };

$count2 = new Count(2);
Assert::assertTrue($count2->evaluate($gen2(), '', true));
Assert::assertFalse($count2->evaluate($gen3(), '', true)); // this should still work

$count3 = new Count(3);
Assert::assertFalse($count3->evaluate($gen2(), '', true));
Assert::assertTrue($count3->evaluate($gen3(), '', true)); // this should still work
```

Maybe need to reset `$this->countOfGenerator = null;` at the beginning of `function matches`?

Also please consider https://github.com/sebastianbergmann/phpunit/issues/3302#issuecomment-421365917 (i.e. there are non-`Countable`, `Traversable` things that are _not_ `instanceof Generator` but suffer the same kind of problem)...

**Comment by JeroenDeDauw** [comment]
I can confirm that this PR is breaking that behavior and does not clean up the already existing confusion between Generators and Iterables that cannot be rewinded. I'll submit a modified solution in a bit

**Comment by sebastianbergmann** [comment]
Superseded by #3316.

**Pull request closed without merging**
