### PR TITLE
Housekeeping: improve tearDownAfterClass handling

### PR DESCRIPTION
**Pull request by epdenouden**
While working on refactoring the [basic test collection](#3453) I bumped into some rough edges working with fixtures. Exceptions during `TestSuite` tear down are now logged, reusing the last test to keep output readable:

image

### CODE REVIEW

**Comment by epdenouden** [comment]
It's line endings, will fix later today 🔬

**Comment by sebastianbergmann** [comment]
Odd that the tests fail on PHP < 7.4.

**Comment by epdenouden** [comment]
> Odd that the tests fail on PHP < 7.4.

It is a strange failure and it does have to do with the mixed use of `\n` and `PHP_EOL` around exception message handling. I noticed it first when colorizing the testdox printer. A risky test with custom message would also have an extra empty line that I never figured out back then. I will find it :)

**Comment by sebastianbergmann** [comment]
Yay!, it's green.

**Comment by epdenouden** [comment]
> Yay!, it's green.

Oh wow. I'm so proud! haha

Anyway: the line endings used all over the code turn out to be a mix of `\n` and `PHP_EOL`. The only way to get the output stable is to manually filter every line in a few places to make sure nothing slips through.

**Pull request merged**
