### PR TITLE
Adding assertArrayStructure

### PR DESCRIPTION
**Pull request by MmdohAhmd**
This assertion makes sure that an array conforms to a given structure.

`$strict` parameters makes the assertion fail if there are one or more elements that are present in `$array` but not present in `$expectedStructure`  

Examples: 

```php
        
        $expected = [
            'a',
            'b',
            'c' => ['d', 'e'],
        ];

        $actual = [
            'a' => 'aval',
            'b' => 'bval',
            'c' => ['d' => 'dval', 'e' => 'eval'],
            'f',
        ];

        $this->assertArrayStructure($expected, $actual); //should pass
        $this->assertArrayStructure($expected, $actual, true); //should NOT pass

```

```php
        
        $expected = [
            'a',
            'b',
            'c'
        ];

        $actual = [
            'a' => 'aval',
            'b' => 'bval',
        ];

        $this->assertArrayStructure($expected, $actual); //should NOT pass

```

### CODE REVIEW

**Comment by keradus** [comment]
:-1: for this Constraint
it proves one needs to switch to named Value Object rather than using random assoc arrays
this Constraint would promote bad practices

**Comment by sebastianbergmann** [comment]
I am with @keradus on this. For the same reason plus the fact that I am reluctant to accept new assertions into the main PHPUnit distribution.

**Comment by sebastianbergmann** [comment]
Thank you for your contribution. I appreciate the time you invested in preparing this pull request. However, I have decided not to merge it.

**Comment by MmdohAhmd** [comment]
NP

**Pull request closed without merging**
