### PR TITLE
Add upper bounds to dependency version ranges

### PR DESCRIPTION
**Pull request by JeroenDeDauw**

### CODE REVIEW

**Comment by sebastianbergmann** [comment]
What is this supposed to accomplish?

**Comment by JeroenDeDauw** [comment]
The prevention of pulling in new major versions of those dependencies without first explicitly specifying PHPUnit is compatible with them

**Comment by GrahamCampbell** [comment]
:+1:

**Comment by sebastianbergmann** [comment]
`master` is not PHPUnit 6 anymore.

**Pull request closed without merging**
