### PR TITLE
Make JUnit's logging of risky tests consistent with other types

### PR DESCRIPTION
**Pull request by oprypkhantc**
Closes https://github.com/sebastianbergmann/phpunit/issues/3937

### CODE REVIEW

**Comment by Fedcomp** [comment]
can this be reviewed?

**Comment by sebastianbergmann** [comment]
TL;DR: A risky test is not an error.

The slightly longer answer: not all features of PHPUnit can be mapped in a sensible way to "JUnit XML", whatever that may be. See #3162.

**Comment by autaut03** [comment]
There's no alternative for risky tests in JUnit xml other than error. 

Hence, PHPUnit reports it as an error currently. The only change this PR introduces is the addition of stack trace and test name. It has always been an error.

**Comment by Fedcomp** [comment]
Thank you for the answer!
In my case i use paratest and i would like to see additional reasons test failed like phpunit does for risky tests.
Right now in paratest i don't even see the script name! so i consider this pull request a reasonable fix for now. I spent a really long time debugging race condition tests in paratest and this pr would probably save me a lot of time.

**Pull request closed without merging**
