### PR TITLE
Chain previous exception in AssertionFailedError

### LINKED ISSUE #5068: AssertionFailedError loses original trace when chaining with a previous exceptions
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 9.5.24
| PHP version         | n/a
| Installation Method | Composer

#### Summary

Identified in #4983 .

When a `AssertionFailedError` is thrown as a re-throw of a previous exception (for instance as part of a `onNotSuccessfulTest()`. callback), and the previous exception is chained in, the failure reported by PHPUnit traces to the part where AssertionFailedError was thrown, and the original trace is lost. So there is no information about where the test failed.

#### Current behavior

```
PHPUnit 9.5.24 #StandWithUkraine

Runtime:       PHP 8.1.10
Configuration: /home/runner/work/d8-unit/d8-unit/core/phpunit.xml.dist

Testing Drupal\Tests\node\Functional\NodeTitleTest
F                                                                   1 / 1 (100%)

Time: 00:06.500, Memory: 10.00 MB

There was 1 failure:

1) Drupal\Tests\node\Functional\NodeTitleTest::testNodeTitle
Title found

/home/runner/work/d8-unit/d8-unit/core/tests/Drupal/Tests/BrowserTestBase.php:441
/home/runner/work/d8-unit/d8-unit/core/tests/Drupal/Tests/Traits/UnsuccessfulTestHandlerTrait.php:16
/home/runner/work/d8-unit/d8-unit/vendor/phpunit/phpunit/src/Framework/TestResult.php:726

FAILURES!
Tests: 1, Assertions: 17, Failures: 1
```

#### How to reproduce

Implement a `onNotSuccessfulTest()` callback in a test, and add logic so that a Throwable is re-thrown as a `AssertionFailedError` with the Throwable chained in. For example,

```
    if ($t instanceof MinkException) {
      throw new AssertionFailedError($t->getMessage(), $t->getCode(), $t);
    }

```
#### Expected behavior

```
PHPUnit 9.5.24 #StandWithUkraine

Runtime:       PHP 8.1.10
Configuration: /home/runner/work/d8-unit/d8-unit/core/phpunit.xml.dist

Testing Drupal\Tests\node\Functional\NodeTitleTest
F                                                                   1 / 1 (100%)

Time: 00:06.500, Memory: 10.00 MB

There was 1 failure:

1) Drupal\Tests\node\Functional\NodeTitleTest::testNodeTitle
Title found

/home/runner/work/d8-unit/d8-unit/core/tests/Drupal/Tests/BrowserTestBase.php:441
/home/runner/work/d8-unit/d8-unit/core/tests/Drupal/Tests/Traits/UnsuccessfulTestHandlerTrait.php:16
/home/runner/work/d8-unit/d8-unit/vendor/phpunit/phpunit/src/Framework/TestResult.php:726

Caused by Behat\Mink\Exception\ExpectationException: Title found
/home/runner/work/d8-unit/d8-unit/core/tests/Drupal/Tests/WebAssert.php:538
/home/runner/work/d8-unit/d8-unit/core/tests/Drupal/Tests/WebAssert.php:281
/home/runner/work/d8-unit/d8-unit/core/modules/node/tests/src/Functional/NodeTitleTest.php:94
/home/runner/work/d8-unit/d8-unit/vendor/phpunit/phpunit/src/Framework/TestResult.php:726

FAILURES!
Tests: 1, Assertions: 17, Failures: 1.
```

### PR DESCRIPTION
**Pull request by mondrake**
Fixes #5068

### CODE REVIEW

**Comment by sebastianbergmann** [comment]
Can you please add a test that fails without and passes with these changes? This probably needs to be an end-to-end PHPT test.

**Comment by mondrake** [comment]
Will try. Do we have to consider traversing the exception chain up to the root one to get the trace at each re-throw, or just getting trace of the previous one is enough?

**Comment by mondrake** [comment]
I cannot find a way to determine from within the exception whether the originating test was being run in isolation or not, so I added a parameter to the exception's constructor to indicate that context. Probably not a very suitable solution, some help would do.

**Comment by mondrake** [comment]
I fixed the code style issues.

I will not disclose my real name in a public environment, sorry. I have committed with name + surname's initial, which is as far as I will go. Thanks for understanding.

**Comment by mondrake** [comment]
Agree this was not viable. Biggest problem was impossibility to determine if a test was run in a process isolation context from within the exception.

Looking forward to a more sustainable solution. Let me know if I can help.

Thanks

**Pull request closed without merging**
