### PR TITLE
add deprecation warning when called with just a class name

### PR DESCRIPTION
**Pull request by realFlowControl**
This adds the deprecation warning when calling PHPUnit with just a class name or class name and filename as discussed in issue #3859 

- [x] add deprecation warning
- [x] fix unit tests

### CODE REVIEW

**Comment by flow-control** [comment]
Hey @sebastianbergmann,
this is ready to be merged, i will prepare the removal than in another PR.
/Flo

**Comment by flow-control** [comment]
@sebastianbergmann should i rebase this on `8.4`, so that we have the deprecation warning in `8` already?

**Comment by sebastianbergmann** [comment]
This branch has conflicts that must be resolved. The target branch should be `master` so that we get this for PHPUnit 8.5 (December 2019).

**Comment by flow-control** [comment]
I rebased on master and solved the conflict, everything green now :smile:

**Comment by flow-control** [comment]
@sebastianbergmann had you time reviewing this?

**Comment by MaXal** [comment]
I'm from the PhpStorm team.
Could you please advise a new recommended way to run a single class or a single method? 
We run a single test using: 
`phpunit --filter "/(::testMe)( .*)?$/" MyTest /Users/maxim.kolmakov/PhpstormProjects/untitled42/MyTest.php `
and a class:
`phpunit MyTest /Users/maxim.kolmakov/PhpstormProjects/untitled42/MyTest.php `

This is quite an essential functionality that a lot of people are using every day and we really don't want to lose it!
image

**Comment by sebastianbergmann** [comment]
@MaXal Using `--filter` would be the "right way":

* `--filter MyTest` will run all tests from `MyTest`
* `--filter MyTest::testMe` will run the single test `testMe` from test class `MyTest`

Also note that we are not deprecating/removing the ability to invoke the PHPUnit test runner with the path to a test case class sourcecode file. We are "just" deprecating/removing the ability to invoke it with only a test case class name.

**Comment by MaXal** [comment]
@sebastianbergmann Thank you for the answer! We will update the line we're using to run tests.

**Pull request merged**
