### PR TITLE
Enhancement: Update shivammathur/setup-php

### PR DESCRIPTION
**Pull request by localheinz**
This PR

* [x] updates `shivammathur/setup-php`

Follows https://github.com/sebastianbergmann/phpunit/issues/4150#issuecomment-605590992.

### CODE REVIEW

**Comment by localheinz** [comment]
@sebastianbergmann 

Are we missing the `COMPOSER_ROOT_VERSION` environment variable here, so dependencies can be properly resolved?

**Comment by sebastianbergmann** [comment]
> Are we missing the `COMPOSER_ROOT_VERSION` environment variable here, so dependencies can be properly resolved?

Don't know. All I know is that I do not need to set `COMPOSER_ROOT_VERSION` locally. `ant setup` "just works" for me.

**Comment by localheinz** [comment]
@sebastianbergmann 

Same for me, but hang on - perhaps we can work around it.

**Comment by sebastianbergmann** [comment]
The change from `shivammathur/setup-php@v1` to `shivammathur/setup-php@v2` should go into `8.5` and be merged from there to `9.0` and `master`.

**Comment by localheinz** [comment]
@sebastianbergmann 

Adjusted!

**Pull request merged**
