### PR TITLE
In callback there is no "file" in trace

### PR DESCRIPTION
**Pull request by DarkSide666**
In callback there is no "file" in trace.

For example, trace will look like
```
    [0] => Array
        (
            [file] => C:\wamp\www\atk4\validate\vendor\vlucas\valitron\src\Valitron\Validator.php
            [line] => 760
            [function] => strtotime
        )
    [1] => Array
        (
            [function] => validateDate
            [class] => Valitron\Validator
            [type] => ->
        )
    [2] => Array
        (
            [file] => C:\wamp\www\atk4\validate\vendor\vlucas\valitron\src\Valitron\Validator.php
            [line] => 1251
            [function] => call_user_func
        )
   ...
```
and `[1]` element has only function, class and type attributes, but no file and line.

### CODE REVIEW

**Comment by sebastianbergmann** [comment]
Thank you for your pull request.

Please include a **minimal**, **self-contained**, reproducing test case that shows the problem you are aiming to solve.

Also note that pull requests for bug fixes should not target `main` but the oldest release branch that still receives bug fixes where the problem exists.

**Comment by DarkSide666** [comment]
I've rebased this PR to `11.1` branch. In versions `10.x` this is not relevant.

Speaking about tests I'm really not sure how to write proper one for phpunit.
This simple test class shows that in case `debug_backtrace` is called from callback method, then it do not contain `file` and `line` array keys. So asserting that `file` and `line` keys are always present in backtrace in phpunit ErrorHandler class is wrong and will throw error in such  cases.

```
class MyTest extends TestCase
{
    public function testDebugBacktrace()
    {
        $result = $this->callUserFuncExample();

        // Check if the debug_backtrace has been generated
        $this->assertNotNull($result);

        // Check if the first element of the debug_backtrace is missing file and line elements
        $this->assertArrayHasKey('function', $result[0]);
        $this->assertArrayNotHasKey('file', $result[0]);
        $this->assertArrayNotHasKey('line', $result[0]);
    }

    private function callUserFuncExample()
    {
        return call_user_func([$this, 'exampleCallback']);
    }

    private function exampleCallback()
    {
        return debug_backtrace(DEBUG_BACKTRACE_PROVIDE_OBJECT, 1);
    }
}```

**Comment by DarkSide666** [comment]
Added testcase which after fix will no more fail, but before fix fails.

**Comment by mvorisek** [comment]
@sebastianbergmann this PR should be retarget instead of closed

**Comment by sebastianbergmann** [comment]
@DarkSide666 I did not intend to close this. Please send a new PR against the `11.2` branch. Thanks!

**Comment by sebastianbergmann** [comment]
Merged manually into `11.2`.

**Pull request closed without merging**
