### PR TITLE
Implement option to disable Testdox progress animation

### PR DESCRIPTION
**Pull request by epdenouden**
Implements #3513 allowing the user to disable the Testdox progress animation.

#### Changes ####
- add `--no-interaction` command line option
- add `noInteraction` attribute for XML-configuration files
- update configuration unit tests and CLI option tests

Unfortunately I did not manage to get a screenshot.

### CODE REVIEW

**Comment by sebastianbergmann** [comment]
Thanks!

I am not sure I like the `--no-progress` and `noProgress` names. They can be misunderstood as "no progress output at all".

**Comment by epdenouden** [comment]
Agreed, the dot-printer also shows progress without animation. It seems --no-progress is relatively common as a GNU-style --arg

I'll change it to '--no-spinner' as I don't think there'll be any other new animations

**Comment by sebastianbergmann** [comment]
Sounds reasonable. Thanks!

**Comment by epdenouden** [comment]
While changing the name I just noticed this that composer has a `--no-interaction` flag which seems perfect and is already used by another large PHP project. Even better I think :)

**Pull request merged**
