### PR TITLE
fix error if run phpunit-9.phar having phpunit/phpunit:^9 in vendor

### PR DESCRIPTION
**Pull request by fizzka**
Problem: when running phpunit-9.phar on a project having phpunit/phpunit (>=9.1) in vendor getting an error:
```
$ php phpunit-9.phar
PHP Fatal error:  Cannot redeclare PHPUnit\Framework\assertArrayHasKey() (previously declared in phar:///home/ilya/bin/phpunit/phpunit/Framework/Assert/Functions.php:80) in /home/ilya/projects/phpunit/src/Framework/Assert/Functions.php on line 79
```

referrenced issues:
#4094
#4038

### CODE REVIEW

**Comment by sebastianbergmann** [comment]
Thank you for your contribution. I appreciate the time you invested in preparing this pull request. However, I have decided not to merge it.

**Comment by fizzka** [comment]
Do you have any reason to ignore with problem?

**Comment by githoober** [comment]
I am being affected by this problem at the moment. @fizzka did you find any workaround?

@sebastianbergmann Is there a reason you decided not to merge it?

**Comment by fizzka** [comment]
@githoober sorry, I can't find more apropriate solution for this case.
I disagree with @sebastianbergmann and still feel a big inconvenience.

**Pull request closed without merging**
