### PR TITLE
Support for Cobertura XML report format

### PR DESCRIPTION
**Pull request by smmccabe**
Cobertura options to for once https://github.com/sebastianbergmann/php-code-coverage/pull/812 gets merged in.

There is 1 type check failing that I don't understand. It references a method that hasn't been changed with this patch so I am unclear as to why it is failing now and doesn't on master. I haven't used psalm before though so maybe I am just missing something.

### CODE REVIEW

**Comment by smmccabe** [comment]
Figured out the type checker issue, fixed.

**Comment by DanielBadura** [comment]
Oh wow nice! Just discovered a new feature in GitLab that needs the cobertura report (https://about.gitlab.com/releases/2020/09/22/gitlab-13-4-released/#inline-code-coverage-remarks-inside-mr-diffs).

Gonna try this out the next days 😈 
Thanks alot!

**Comment by Xplouder** [comment]
@DanielBadura did you try this feature?

@sebastianbergmann Looks like you closed this PR. Any special reason to not include this feature? Thank you.

**Comment by DanielBadura** [comment]
Yeah it tried to try it :D
Couldnt get it really to work with GitLab. I didnt had much time toinvestigate it any further.

its not just closed, the feature is in phpunit ;o

**Pull request closed without merging**
