### PR TITLE
Use symfony/process to run isolated tests

### LINKED ISSUE #1342: Replace PHP process isolation code with Symfony Process component
Platform-specific process isolation bugs like #1340 are exceptionally hard to debug.

The [Symfony Process component](https://github.com/symfony/process) is a decoupled and very lightweight library.  In essence, a robust wrapper around `proc_open()`.

Proposal:  Replace the `PHPUnit_Util_PHP_*` classes with Symfony `Process`.

Doing this should be relatively straightforward.  However, I don't know whether the backwards compatibility policy also applies to rather internal code of the test runner itself?

### PR DESCRIPTION
**Pull request by rpkamp**
Replaces https://github.com/sebastianbergmann/phpunit/pull/3117 - I had deleted the fork for that PR, so I can't push to it anymore

Fixes https://github.com/sebastianbergmann/phpunit/issues/1342

Can only be merged once https://github.com/sebastianbergmann/phpunit/issues/2015 lands

### CODE REVIEW

**Comment by ADmad** [comment]
I just hope this doesn't cause version conflict issues with libs/projects/apps already having `symfony/process` as dependency.

**Comment by rpkamp** [comment]
That's why it will be included in the scoped phar file, once that's there :)

**Comment by sebastianbergmann** [comment]
Thank you for your contribution. I appreciate the time you invested in preparing this pull request. However, I have decided not to merge it.

**Comment by rpkamp** [comment]
Might I ask why?

**Comment by rpkamp** [comment]
Ah, just saw [this comment](https://github.com/sebastianbergmann/phpunit/issues/1342#issuecomment-584738268) - never mind.

**Pull request closed without merging**
