### PR TITLE
Allow doubling `readonly` classes

### PR DESCRIPTION
**Pull request by drealecs**
There is currently a problem with implementing mocks for readonly classes and the only impediment so far is that mocks have mutable internal state as explained here: https://github.com/sebastianbergmann/phpunit/issues/5353#issuecomment-1535696396

This PR is moving phpunit internal state associated with stub/mock classes/objects to separate global classes.

Moved state from stubs and mock objects:
- private static array $__phpunit_configurableMethods
- private bool $__phpunit_returnValueGeneration
- private ?InvocationHandler $__phpunit_invocationMocker
- private static array $__phpunit_deprecation_emitted_for_test
- private object $__phpunit_originalObject

to two singleton internal classes, `InternalStubState`  and `InternalMockObjectState` that store the state in
- an array with class name as key for previously static state
- a WeakMap with objects as key for previously instance state

not introducing new memory leaks issues.

And also implements readonly doubles for readonly classes that now is possible.

### CODE REVIEW

**Comment by drealecs** [comment]
I realize this is conflicting with further changes in main but so far it seems that changes can be ported easily there as well.

**Comment by sebastianbergmann** [comment]
Thank you for your contribution. I appreciate the time you invested in preparing this pull request. However, these changes have to be made in `main`.

**Comment by drealecs** [comment]
Yes, that sounds better.
It could be eventually backported if really needed but sounds like a feature that can go into the next major version.

Will do the changes and retarget PR.

**Comment by sebastianbergmann** [comment]
> It could be eventually backported

Definitely not, sorry. Unfortunately, I also have to dampen hopes that this will be merged soon as at first glance I am not happy with the implementation (static method calls). I hope to provide more useful feedback later, but I am currently busy with other things.

**Comment by drealecs** [comment]
> Unfortunately, I also have to dampen hopes that this will be merged soon as at first glance I am not happy with the implementation

No worries, I opened the PR to have a place for discussion.
If there is solution, I'm sure we can find the best one. If not, it was good learning a bit more the internals.

> I am currently busy with other things.

Nothing urgent. Let's take the time to find what's best for phpunit.

**Comment by speller** [comment]
I'm sorry for getting into this thread, but I have some thoughts regarding the implementation. The current approach is basically implemented in this way:

```php
readonly class ToBeDoubled {
}

trait MockObjectApi {
    private object $__phpunit_originalObject;

    public function __phpunit_setOriginalObject(object $originalObject): void
    {
        $this->__phpunit_originalObject = $originalObject;
    }
    ...
}

class GeneratedMock extends ToBeDoubled {
    use MockObjectApi;
}
```

The problem is obviously in the generated class that it can not be inherited from a readonly class.

Can we implement the readonly support in the following way to not use static calls?

```php
readonly class ToBeDoubled {
}

trait MockObjectApi {
    private object $__phpunit_originalObject;
}

trait ReadonlyMockObjectApi {
    private readonly WriteableState $__phpunit_state;

    public function __phpunit_setOriginalObject(object $originalObject): void
    {
        $this->__phpunit_state->__phpunit_originalObject = $originalObject;
    }
}

class WriteableState {
    use MockObjectApi;
}

readonly class GeneratedMock extends ToBeDoubled {
    use ReadonlyMockObjectApi;

    public function __construct(...)
    {
        $this->__phpunit_state = new WriteableState();
        parent::__construct(...);
    }
}
```

This requires the whole `MockObjectApi` to be copy-pasted into `ReadonlyMockObjectApi` but use the state field to write to `__phpunit_originalObject` field. To avoid this copy-pasting, the whole doubling can be moved to the new design, and always use the `WriteableState` even for non-readonly doubled classes:

```php
readonly class ToBeDoubled {
}

trait MockObjectApi {
    // No $__phpunit_state field

    public function __phpunit_setOriginalObject(object $originalObject): void
    {
        $this->__phpunit_state->__phpunit_originalObject = $originalObject;
    }
}

class WriteableState {
    private object $__phpunit_originalObject;
}

// Readonly mocks are generated with the additional readonly field and constructor:
readonly class GeneratedMock extends ToBeDoubled {
    use MockObjectApi;
    private readonly WriteableState $__phpunit_state;

    public function __construct(...)
    {
        $this->__phpunit_state = new WriteableState();
        parent::__construct(...);
    }
}

// Non-readonly mocks are generated with the additional writeable field (to support older PHP versions):
class GeneratedMock extends ToBeDoubled {
    use MockObjectApi;
    private WriteableState $__phpunit_state;

    public function __construct(...)
    {
        $this->__phpunit_state = new WriteableState();
        parent::__construct(...);
    }
}
```
The only issue is that we still can not double readonly classes with private constructors but I guess this is a very rare case. It's still much better than no support for readonly classes.

What do you think?

**Comment by pzarfos** [comment]
## PR Analysis

- 🎯 **Main theme:** Implementing mocks for readonly classes in PHPUnit
- 📝 **PR summary:** This PR aims to solve the problem of implementing mocks for readonly classes in PHPUnit. It does this by moving the mutable internal state associated with mock classes/objects to a separate global class. The PR also implements readonly doubles for readonly classes.
- 📌 **Type of PR:** Enhancement
- 🧪 **Relevant tests added:** Yes
- ⏱️ **Estimated effort to review [1-5]:** 4, because the PR involves a significant change in the PHPUnit's core functionality, and requires a deep understanding of the PHPUnit's internals and PHP's readonly classes.
- 🔒 **Security concerns:** No security concerns found
## PR Feedback

- 💡 **General suggestions:** The PR is well-structured and the changes are logically organized. The use of a singleton class to manage the internal state of the mock objects is a good approach. However, it would be beneficial to ensure that the singleton pattern is correctly implemented and thread-safe. Also, it would be helpful to add more comments explaining the logic behind the changes, especially for developers who are not familiar with the PHPUnit's internals.


- <details><summary> 🤖 Code feedback:</summary>


  - **relevant file:** ``src/Framework/MockObject/Runtime/Api/InternalState.php``  
   **suggestion:** Consider adding thread-safety to the singleton implementation. This can be achieved by using a lock or a mutex to ensure that only one thread can access the getInstance() method at a time. [important]  
   **relevant line:** [public static function getInstance(): self](https://github.com/sebastianbergmann/phpunit/pull/5429/files#diff-732c64c1362016a7fb407dc0ee11b3d81750ce41ba4bad3fc818051c625739fcR41)  


  - **relevant file:** ``src/Framework/MockObject/Generator/Generator.php``  
   **suggestion:** It's a good practice to avoid using magic strings. Consider defining 'readonly' as a constant. [medium]  
   **relevant line:** [$buffer .= 'readonly ';](https://github.com/sebastianbergmann/phpunit/pull/5429/files#diff-138f3378f405302a141eb6fc0a475bc902c03276193b5269296ba1d6265b31e2R824)  


  - **relevant file:** ``src/Framework/MockObject/Runtime/Api/InternalState.php``  
   **suggestion:** Consider adding type hints to the method parameters for better code readability and to prevent potential bugs. [medium]  
   **relevant line:** [public function initConfigurableMethods(string $class, array $configurableMethods): void](https://github.com/sebastianbergmann/phpunit/pull/5429/files#diff-732c64c1362016a7fb407dc0ee11b3d81750ce41ba4bad3fc818051c625739fcR58)  


  - **relevant file:** ``src/Framework/MockObject/Runtime/Api/InternalState.php``  
   **suggestion:** It's a good practice to avoid using magic strings. Consider defining 'InvocationHandler' as a constant. [medium]  
   **relevant line:** [public function getInvocationHandler(string $class, object $mock): InvocationHandler](https://github.com/sebastianbergmann/phpunit/pull/5429/files#diff-732c64c1362016a7fb407dc0ee11b3d81750ce41ba4bad3fc818051c625739fcR71)  

</details>

**Comment by drealecs** [comment]
Hey @sebastianbergmann!
I just rebased and updated the PR with some renamed, hoping it looks a bit better now.

I would appreciate if you could take some time to review the changes and to offer some feedback.
In case this PR has some good parts but more work will be needed, I would like to make sure there is enough time to include it in PHPUnit 11 that has a minimum PHP version of 8.2 (the same version where readonly classes were introduced).
Of course, that's up to you and your time availability.

The only thing I can think of so far is to remove the internal state classes singleton pattern and the `getInstance()` call and directly use static class properties and methods, but that would make it a bit harder to instantiate the `WeakMap`.

Thanks!

**Comment by sebastianbergmann** [comment]
I plan to address this issue in time for PHPUnit 11.

**Comment by sebastianbergmann** [comment]
Thank you for your contribution. I appreciate the time you invested in preparing this pull request and am truly sorry that it took me so long to review this. I am also sorry that I do not like the implementation.

If we have a `private readonly SomeClass $someObject` property then the only effect that `readonly` has is that an object can only be assigned once using the `=` operator to that property. The object that is assigned to the `readonly` property does not have to be of a class that is `readonly` and may be mutable.

I would prefer an implementation that encapsulates the mutable state used by the test double system in an object. This object can then be assigned to a `readonly` property in the generated test double code. I would appreciate it a lot if you, @drealecs, could send a new pull request that implements this idea instead of the static solution implemented in this pull request.

No matter who ends up implementing this, @drealecs, me, or somebody else, I believe the change could end up being small enough so that it could be included in a future PHPUnit 10.5 bugfix release.

Please note that support for doubling `readonly` classes is still not a priority for me as I do not think `readonly` classes should be doubled. Either your `readonly` class is an immutable value object: great, you do not need to double that. Or your `readonly` class is a service (or processor) then that class should implement an interface and you should double that instead of the implementing class.

**Comment by drealecs** [comment]
Hi @sebastianbergmann, thank you for the time to review.

I was not so happy with the static methods as well, but I wasn't able to identify a better option myself, so thank you for the feedback.
I changed the implementation, and it was pretty straightforward with the small difference that I had to initiate the state in the generator after instantiation.
There is one small issue with the static properties like `$__phpunit_configurableMethods`, as readonly classes don't allow static properties (as it could have been a static readonly property if such feature would exist), and I had to keep them as static methods in the state classes.

Overall, I think it looks better, and I remade the commit where I moved the state and pushed on the same branch. If you want, you can reopen this same PR. I'll make sure to fix the pipeline in case there are other issues and update the description as well.
Or I can open a new PR, however you prefer.
Thank you again!

**Comment by sebastianbergmann** [comment]
Don't know why, but the "Reopen and comment" button is disabled. I would suggest that you send a new pull request. Feel free to target the `10.5` branch.

**Pull request closed without merging**
