### PR TITLE
Enhancement: Update `actions/upload-artifact` and `actions/download-artifact`

### LINKED ISSUE #5684: Migrate to `actions/upload-artifact@v4` and `actions/download-artifact@v4`
We currently use Migrate to `actions/upload-artifact@v3` and `actions/download-artifact@v3` which use Node 16.

The use of Node 16 is [deprecated](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/) on GitHub Actions.

We need to migrate to `actions/upload-artifact@v4` and `actions/download-artifact@v4` so that our build pipeline keeps working when GitHub Actions no longer supports Node 16.

See https://github.com/actions/upload-artifact/blob/main/docs/MIGRATION.md for details.

### PR DESCRIPTION
**Pull request by localheinz**
This pull request

- [x] updates `actions/upload-artifact` and `actions/download-artifact`

Related to #5684.

### CODE REVIEW

**Comment by sebastianbergmann** [comment]
I did not expect this to be a simple as that :)

**Comment by sebastianbergmann** [comment]
Looks like the pipeline was not run:

> Workflow runs completed with no jobs

**Comment by localheinz** [comment]
Looks like it was a little hiccup with GitHub Actions, @sebastianbergmann!

**Comment by sebastianbergmann** [comment]
Thank you!

**Pull request merged**
