### PR TITLE
JUnit: report Risky test consistently as an error

### PR DESCRIPTION
**Pull request by Slamdunk**
Close https://github.com/sebastianbergmann/phpunit/issues/3937

### CODE REVIEW

**Comment by sebastianbergmann** [comment]
Have you seen https://github.com/sebastianbergmann/phpunit/issues/3913#issuecomment-680645331? Is your change compatible with Jenkins, etc.? In other words: are you sure this has no unintended side effects?

**Comment by Slamdunk** [comment]
> Are you sure this has no unintended side effects?

If you are asking me to bet my kids' lifes, no.
But I'm altering only the content of the XML tag, which is by that XSD definition a free string.
Until https://github.com/sebastianbergmann/phpunit/issues/4321 gets implemented, this PR is essential for ParaTest because, as of yet, we get zero information about the failure otherwise:

```
There were 3 errors:

1) Risky Test

2) ParaTest\Tests\fixtures\failing_tests\UnitTestWithErrorTest::testTruth
RuntimeException: Error!!!

./paratest/test/fixtures/failing_tests/UnitTestWithErrorTest.php:21

3) Risky Test
```

May I ask you how to fix the errors reported in CI?

```diff
-    <testcase name="testWarning" class="PHPUnit\SelfTest\Basic\StatusTest" classname="PHPUnit.SelfTest.Basic.StatusTest" file="%s%eStatusTest.php" line="%d" assertions="0" time="%f">
+    <testcase name="testWarning" class="PHPUnit\SelfTest\Basic\StatusTest" classname="PHPUnit.SelfTest.Basic.StatusTest" file="/home/runner/work/phpunit/phpunit/tests/basic/unit/StatusTest.php" line="57" assertions="0" time="0.000091">
```

I have honestly no idea what's going on in these test results :confused:

**Comment by sebastianbergmann** [comment]
> If you are asking me to bet my kids' lifes, no.
> But I'm altering only the content of the XML tag, which is by that XSD definition a free string.

Okay.

> I have honestly no idea what's going on in these test results 😕

Me neither, I'll have a look ASAP.

**Comment by sebastianbergmann** [comment]
*sigh*, the tests are still failing on Windows.

**Pull request merged**
