### PR TITLE
Fix invalid reference to ArrayAccess

### PR DESCRIPTION
**Pull request by muglug**

### CODE REVIEW

**Comment by sebastianbergmann** [comment]
`src/Framework/Assert/Functions.php` is a generated file. Any change must be implemented in `build/scripts/generate-global-assert-wrappers.php`, the script that generates the file.

**Comment by sebastianbergmann** [comment]
@localheinz Thanks! Can you make this against `9.3`, please? Thanks!

**Comment by localheinz** [comment]
@muglug @sebastianbergmann 

I think this should be good!

**Comment by muglug** [comment]
Thanks, sorry - last couple of days have been very busy

**Pull request merged**
