### PR TITLE
1 test, 0 assertion

### PR DESCRIPTION
**Pull request by ftwbzhao**
``` php
public function testLogic()
{
//$this->markTestSkipped('todo');
}
```

```
#when numAssertions = 0
OK (1 test, 0 assertions)
```

### CODE REVIEW

**Comment by sebastianbergmann** [comment]
Not sure what you are trying to report / fix.

```php
<?php
class Test extends PHPUnit_Framework_TestCase
{
    public function testOne()
    {
    }
}
```
```
`$ phpunit Test
PHPUnit 4.6.5 by Sebastian Bergmann and contributors.

.

Time: 94 ms, Memory: 5.00Mb

OK (1 test, 0 assertions)
```

**Comment by ftwbzhao** [comment]
Actual
```
OK (1 test, 0 assertion)
```

**Comment by sebastianbergmann** [comment]
As you can see in https://github.com/sebastianbergmann/phpunit/pull/1699#issuecomment-97322120, I cannot reproduce that.

**Comment by ftwbzhao** [comment]
```php
$this->numAssertions == 0
```
Why append 's'?

**Comment by ftwbzhao** [comment]
Expected

```
OK (1 test, 0 assertion)
```

Actual

```
OK (1 test, 0 assertions)
```

**Comment by sebastianbergmann** [comment]
It's "0 assertions", "1 assertion", "2 assertions", "3 assertions", ...

**Comment by ftwbzhao** [comment]
Why 0 use “assertions” ?

**Comment by GrahamCampbell** [comment]
> Why 0 use “assertions” ?

Because that's correct English...

**Comment by ftwbzhao** [comment]
..err

Why 1 use "assertion" ?

**Comment by ftwbzhao** [comment]
..err

**Pull request closed without merging**
