### PR TITLE
Use symfony/process to run isolated tests

### LINKED ISSUE #1342: Replace PHP process isolation code with Symfony Process component
Platform-specific process isolation bugs like #1340 are exceptionally hard to debug.

The [Symfony Process component](https://github.com/symfony/process) is a decoupled and very lightweight library.  In essence, a robust wrapper around `proc_open()`.

Proposal:  Replace the `PHPUnit_Util_PHP_*` classes with Symfony `Process`.

Doing this should be relatively straightforward.  However, I don't know whether the backwards compatibility policy also applies to rather internal code of the test runner itself?

### PR DESCRIPTION
**Pull request by rpkamp**
Fixes #1342

### CODE REVIEW

**Comment by sebastianbergmann** [comment]
Thank you for working on this, @rpkamp. However, this will have to wait until #2015 is implemented.

**Comment by rpkamp** [comment]
That's okay. Tests for windows are still failing anyway. Will look at that later.

**Comment by rpkamp** [comment]
I've checked to see if I could fix the errors in AppVeyor and ran into the following:

`C:\phpunit\tests\TextUI\phpt-args.phpt`:

The problem here is that the argument supplied in `ARGS` in the `.phpt` file is passed with a trailing `\n`, which doesn't seem to matter on *nix, but on windows, the supplied value is literally `help\n`, which isn't equal to `help`, so the test fails. I could change the test to `if ($argc > 0 && strpos($argv[1], 'help') === 0)` and then it would succeed, but it is a break in functionality that others might run into as well. Not really sure how to correctly solve this without any BC breaks. Input would be appreciated.

`C:\phpunit\tests\Regression\GitHub\1348.phpt`

This one is even tougher, as `symfony/process` doesn't use regular STDOUT/STDERR on windows as there are several problematic bugs around it. Instead it redirects all OUT/ERR to files. This means that writing to STDOUT from the test file will _not_ be sent to the terminal, but to the file that STDOUT is redirected to instead. This also a BC break that I don't see a nice way of working around. Again, input would be appreciated.

**Comment by rpkamp** [comment]
Replaced by https://github.com/sebastianbergmann/phpunit/pull/3117

**Pull request closed without merging**
