### PR TITLE
only enable colors when output to a terminal (not to a file)

### PR DESCRIPTION
**Pull request by remicollet**

### CODE REVIEW

**Comment by Fludimir** [comment]
Looks like this commit breaks colors display when running on windows in cygwin terminal

**Comment by GrahamCampbell** [comment]
@Fludimir Lots of things have changed since this.

**Comment by Fludimir** [comment]
May be, but after update from phpunit 4.3.5 to 4.4.1 colors aren't displayed in console and probably no way to display it.

**Comment by GrahamCampbell** [comment]
Yeh, try out phpunit alpha, 4.6.x. It's got the new behaviour in.

**Comment by Fludimir** [comment]
Tried, works only with --colors=always in console. So the only way to display colors in cygwin console will be to manually add this option each run?

**Pull request merged**
