### PR TITLE
Enhancement: Run php-cs-fixer using GitHub Actions

### PR DESCRIPTION
**Pull request by localheinz**
This PR

* [x] runs `friendsofphp/php-cs-fixer` (as installed with `phive` to `/tools`) as GitHub action

### CODE REVIEW

**Comment by localheinz** [comment]
@sebastianbergmann 

I believe the GitHub workflow is not triggered here as I'm only a contributor (as opposed to an owner or collaborator) and adding a workflow could be a security issue.

It works fine in https://github.com/localheinz/playground/pull/1, though!

**Comment by oliverklee** [comment]
This PR now needs a rebase after the most recent changes.

**Review by Ocramius — CHANGES_REQUESTED** [review]
There's a basic issue with this problem (to be dug up in the github docs): the action is only run post-merge.

That's a blocker to get this merged, IMO.

**Comment by sebastianbergmann** [comment]
Can you target `7.5`, please? Thanks!

**Comment by localheinz** [comment]
@sebastianbergmann 

Retargeted!

**Comment by localheinz** [comment]
Thank you, @sebastianbergmann!

**Pull request merged**
