### PR TITLE
Automatically use latest PHP minor version for AppVeyor

### PR DESCRIPTION
**Pull request by epdenouden**
Implement the suggestion by @weltling in https://github.com/sebastianbergmann/phpunit/issues/3419#issuecomment-453862347

No `*-latest.tzg` link for Xdebug yet, but this is one less thing to worry about. @IchHabRecht if you have ideas to improve this further :-)

### CODE REVIEW

**Comment by epdenouden** [comment]
@sebastianbergmann I've implemented the `*-latest` package for PHP 7.2. Once Xdebug becomes 7.3.* compatible I'll update the CI.

**Comment by sebastianbergmann** [comment]
Should this not go into older branches, too?

**Comment by epdenouden** [comment]
You are right of course! I will make a clean pull that works in 7.x, too.

**Comment by epdenouden** [comment]
Ah, I see the 7.5.x branch uses PHP 7.1.x still. It seems we don't need the _latest_ PHP+Xdebug for the v7 family or.. perhaps I am missing the point?

**Comment by epdenouden** [comment]
@sebastianbergmann Don't think this will work for the 7.x branch as the `*-latest` redirect doesn't work for https://windows.php.net/downloads/releases/archives/php-7.1-Win32-VC14-x86-latest.zip

**Pull request merged**
