### PR TITLE
#4204: Show actual data in failed description for assertIsEmpty

### PR DESCRIPTION
**Pull request by pwsdotru**
For issue https://github.com/sebastianbergmann/phpunit/issues/4204

### CODE REVIEW

**Comment by sebastianbergmann** [comment]
Thank you for your contribution. I appreciate the time you invested in preparing this pull request. However, I have decided not to merge it as I believe that #4204 should be addressed in the TeamCity logger instead.

**Comment by sebastianbergmann** [comment]
It might actually make sense to show the contents of an array when it is not empty but was used with `assertIsEmpty()`. I got confused there for a moment because I started looking at this from the TeamCity angle of #4204.

**Comment by sebastianbergmann** [comment]
This branch has conflicts that must be resolved.

**Comment by pwsdotru** [comment]
@sebastianbergmann Thank you for your review and comments. I fixed conflicts.

**Comment by sebastianbergmann** [comment]
Thank you for your contribution. I appreciate the time you invested in preparing this pull request. However, I have decided not to merge it.

**Comment by FeBe95** [comment]
@sebastianbergmann Is there a specific reason, why this PR wasn't merged? Or to phrase it differently: I there anything we could improve, in order for it to get merged?

I feel like this PR adds a very nice QoL improvement when working with `->assertEmpty()`!

**Pull request closed without merging**
