### PR TITLE
Throw an explicit error when key is of invalid type

### PR DESCRIPTION
**Pull request by BackEndTea**
I'm not 100% sure what the best way would be to test this.

### CODE REVIEW

**Comment by sebastianbergmann** [comment]
I will have a look at this after I have merged the `issue-4502/php-8-attributes` branch. Alternatively, you are welcome to send a pull request against that branch.

**Comment by sebastianbergmann** [comment]
> 
> 
> I will have a look at this after I have merged the `issue-4502/php-8-attributes` branch. Alternatively, you are welcome to send a pull request against that branch.

We will need this fix for PHPUnit 9.5 anyway.

**Comment by BackEndTea** [comment]
> We will need this fix for PHPUnit 9.5 anyway.

So send this MR against the 9.5 branch, and make a new one for the master?

**Comment by sebastianbergmann** [comment]
> So send this MR against the 9.5 branch

You can do that, yes. Otherwise I will cherry-pick the commit to `9.5`.

> and make a new one for the master?

You do not have to do that, I'll take care of that. Thanks!

> or will `issue-4502/php-8-attributes` be merged into 9.5?

That branch will be merged into `master` for PHPUnit 10.

**Comment by BackEndTea** [comment]
I've targeted 9.5 now

**Pull request closed without merging**
