### PR TITLE
ref #2236 - Move status assignment after last occurence of _e AND add…

### PR DESCRIPTION
**Pull request by Morerice**
I think that this is what @rtwo was referring to in #2236

### CODE REVIEW

**Comment by keradus** [comment]
as a bug, would be great to fix it on lowest maintained branch, not on not-yet-released phpunit 7 (major, bc breakers)

**Comment by sebastianbergmann** [comment]
Cherry-picked into `6.5` and `master`, backported to `5.7`. Thanks!

**Comment by CDJojn** [comment]
@bigaltum Is it bug or wanted behavior? We are currently facing this issue, all our failing tests are marked as PASSED (internal state) because of TestCase::hasFailed() returns false...

**Comment by sebastianbergmann** [comment]
@bigaltum @CDJojn Please open a new ticket and provide a **minimal**, **self-contained**, reproducing test case that shows your problem.

Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.

**Comment by CDJojn** [comment]
@sebastianbergmann Thank you for your reply. It seems my issue is duplicate of this bug https://github.com/sebastianbergmann/phpunit/issues/3031 - comment added.

**Pull request closed without merging**
