### PR TITLE
Fix issue with variadic parameters not being passed like they should

### PR DESCRIPTION
**Pull request by marac19901990**
**Issue:**
  - #5455 variadic arguments not being passed to closure

**Solution:**
  - fixed the issue and changed the tests to reflect the changes

### CODE REVIEW

**Comment by sebastianbergmann** [comment]
Does this problem also exist in PHPUnit 9.6?

**Comment by marac19901990** [comment]
> Does this problem also exist in PHPUnit 9.6?

I forgot to check, I'll check and update if needed, my guess is that it doesn't work there either

**Comment by marac19901990** [comment]
> Does this problem also exist in PHPUnit 9.6?

It can't be fixed in 9.6, I made a pull request but then realized that array unpacking for string indexed elements is not supported prior to php 8.1.  I'll update the 10.5 pull request with a better solution, but nothing to be done for 9.6

**Comment by sebastianbergmann** [comment]
Cherry-picked into `10.5` and merged to `main` from there. Thanks!

**Comment by marac19901990** [comment]
> Cherry-picked into `10.5` and merged to `main` from there. Thanks!

You didn't have to cherry pick, these are the 10.5 changes, there was another pull request for 9.6 :)

**Comment by sebastianbergmann** [comment]
I know :) I cherry-picked because I wanted to make some additional changes locally before the merge.

**Pull request closed without merging**
