### PR TITLE
Fix Psalm warnings in Constraints

### PR DESCRIPTION
**Pull request by oliverklee**

### CODE REVIEW

**Comment by oliverklee** [comment]
Please don't review or merge … we needs some changes to the php-cs-fixer configuration first.

**Comment by oliverklee** [comment]
NB: This is the PR for 8.3 and master. I'll hand-craft a separate PR for 7.5.

**Comment by oliverklee** [comment]
Repushed; this PR now is ready for review.

**Comment by oliverklee** [comment]
The test failures doe not seem to be related to the changes in this PR.

**Comment by oliverklee** [comment]
#3853 is the 7.5 backport.

**Comment by oliverklee** [comment]
@sebastianbergmann Did you merge this PR or close it unmerged?

**Comment by sebastianbergmann** [comment]
To be honest, I do not remember why I closed this. Can you send a new pull request against `master`, please? Thanks!

**Comment by oliverklee** [comment]
@sebastianbergmann Done: #3917

**Comment by oliverklee** [comment]
@sebastianbergmann Should I also create a PR for this against 8.4?

**Comment by sebastianbergmann** [comment]
Don't think so. Thanks!

**Pull request closed without merging**
