### PR TITLE
fix regression #3889

### PR DESCRIPTION
**Pull request by realFlowControl**
This pull requests

- [x] adds tests for the regressions from #3889 
- [x] fixes the regression

### CODE REVIEW

**Comment by sebastianbergmann** [comment]
Can you send this against `8.4` please? Thanks!

**Comment by flow-control** [comment]
I rebased onto 8.4 and updated the base repo in this pull request, hope everything is correct ;-)

**Comment by mfn** [comment]
Thanks for the fix, the bug also broke PhpStorm integration with phpunit in certain cases (see https://youtrack.jetbrains.com/issue/WI-49132 ). I can confirm this fixes it. Hope there will be a 8.4.2 release with this soon 🤞

Thanks!

**Comment by sebastianbergmann** [comment]
@mfn Do you mean #3904?

**Comment by mfn** [comment]
@sebastianbergmann it looks to be the same!

In  https://github.com/sebastianbergmann/phpunit/issues/3904#issuecomment-546818344 you suggest to try again, I just did with this:
`composer require --dev phpunit/phpunit:dev-master#ae92be526cfdc89fc37991ec10cee28b82177865 --prefer-dist`

(I picked the current head commit on `8.4` branch)

I'm glad to report back that this seems to work for me! 🎉 

(wheras e.g. `composer require --dev phpunit/phpunit:~8.4` does not)

**Comment by sebastianbergmann** [comment]
Thank you, @mfn.

**Comment by mingyoung** [comment]
image

Hi, @flow-control I upgraded to 8.4.2, seems can't run a single test file.

**Pull request merged**
