### PR TITLE
Fix deprecation warning if trailing slash in path is omitted

### LINKED ISSUE #3983: Deprecation warning given too eagerly
The `Invocation with class name is deprecated` warning is printed when a directory (and not a class name) is given:

```
$ tree
.
├── build
│   └── code-coverage
│       ├── CanvasIterator.php.html
│       ├── Canvas.php.html
│       ├── Color.php.html
│       ├── dashboard.html
│       ├── exceptions
│       │   ├── dashboard.html
│       │   ├── Exception.php.html
│       │   ├── index.html
│       │   ├── InvalidArgumentException.php.html
│       │   └── RuntimeException.php.html
│       ├── index.html
│       ├── Matrix.php.html
│       ├── PortablePixmapMapper.php.html
│       └── Tuple.php.html
├── build.xml
├── phive.xml
├── phpunit.xml
├── psalm.xml
├── README.md
├── src
│   ├── autoload.php
│   ├── CanvasIterator.php
│   ├── Canvas.php
│   ├── Color.php
│   ├── exceptions
│   │   ├── Exception.php
│   │   ├── InvalidArgumentException.php
│   │   └── RuntimeException.php
│   ├── Matrix.php
│   ├── PortablePixmapMapper.php
│   └── Tuple.php
├── tests
│   ├── CanvasTest.php
│   ├── ColorTest.php
│   ├── fixture
│   │   └── 10_20_empty.ppm
│   ├── MatrixTest.php
│   ├── PortablePixmapMapperTest.php
│   └── TupleTest.php
└── tools
    ├── phpab
    ├── php-cs-fixer
    ├── phpunit
    ├── phpunit.phar -> phpunit
    └── psalm

8 directories, 39 files
```
```
$ ./tools/phpunit tests
PHPUnit 8.5.0 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.4.0 with PCOV 1.0.6
Configuration: /usr/local/src/raytracer/phpunit.xml
Warning:       Invocation with class name is deprecated

...................................S.......................       59 / 59 (100%)

Time: 82 ms, Memory: 10.00 MB

There was 1 skipped test:

1) SebastianBergmann\Raytracer\MatrixTest::test_the_product_of_two_matrices_can_be_multiplied_by_its_inverse

/usr/local/src/raytracer/tests/MatrixTest.php:528

OK, but incomplete, skipped, or risky tests!
Tests: 59, Assertions: 385, Skipped: 1.
```

CC @flow-control

### PR DESCRIPTION
**Pull request by realFlowControl**
Fixes #3983 if the trailing slash in path is omitted

### CODE REVIEW

**Comment by sebastianbergmann** [comment]
Can you have a look at the test failures? Thanks!

**Comment by flow-control** [comment]
I am on it. Tricky, because it's working on my local machine ... ;-)

**Comment by flow-control** [comment]
This is a weird problem. There is a file named `tests/end-to-end/regression/GitHub/3983.phpt` and a directory with tests to this named `tests/end-to-end/regression/GitHub/3983/`. In my local setup, a call to `phpunit tests/end-to-end/regression/GitHub/3983` will use the test files from the directory, but in the pipeline it will try to find a test class `3983` in the file `3983.phpt` which does not exist.
I fixed this now by renaming the `phpt` file, but what would be the desired behavior in this case? Should `phpunit` use the file or the directory?

**Comment by sebastianbergmann** [comment]
Weird indeed, but (hopefully) a problem for another day.

**Pull request merged**
