### PR TITLE
Enable TestSuite to use autoloader, clean up bootstrap

### PR DESCRIPTION
**Pull request by epdenouden**
While doing some housekeeping I found this note:

https://github.com/sebastianbergmann/phpunit/blob/c23d78776ad415d5506e0679723cb461d71f488f/tests/bootstrap.php#L19-L20

The root cause is that a new `TestSuite` will simply not look for classnames using the autoloader, causing tests trying `new TestSuite(\SomeClass:class)` to fail. A bit confusing, as it automagically works when the class had been autoloaded beforehand.

**Changes**
- change `TestSuite` to use the autoloader for its `\class_exists()`-check
- ability to create a `TestSuite` with the same name as an existing non-`Test` class
- clean up `tests/bootstrap.php`
- fix two corner cases in tests that popped up because of the autoloader change

### CODE REVIEW

**Comment by epdenouden** [comment]
@sebastianbergmann Both issues were indeed related to how the `TestSuite` constructor looks and then instantiates the test classes.

Allowing the constructor to just create an empty `TestSuite` when the provided class(name) isn't a `Test` fixes #2726 without any negative side-effects. Once the `TestSuite` has been created with only a name and no contents, the `getName()` isn't used for potentially risky lookups anymore.

I have tried it via `phpunit.xml` by sticking a single test in a `<testsuite>` with the name of a builtin class and that works fine, see below. The `TestSuiteTest` has been updated to reflect the change.

```
./phpunit --list-suites

PHPUnit 7.5.1-3-g3bc689926 by Sebastian Bergmann and contributors.

Available test suite(s):
 - unit
 - end-to-end
 - DateTime
```

```
./phpunit --testsuite DateTime

PHPUnit 7.5.1-3-g3bc689926 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.2.11 with Xdebug 2.6.0
Configuration: /Users/ewout/proj/phpunit-new-order/phpunit.xml

R                                                                   1 / 1 (100%)

Time: 123 ms, Memory: 4.00MB

There was 1 risky test:

1) OneTestCase::testCase
This test did not perform any assertions

/Users/ewout/proj/phpunit-new-order/tests/_files/OneTestCase.php:18
[...]
```

I originally started working on this for 7.5.x and with the `TestSuite("anyNameNow")` it might be worth a 7.x maintainance update.

**Comment by sebastianbergmann** [comment]
By "it might be worth a maintainance update" you mean this should go into `7.5` instead of `master`?

**Comment by epdenouden** [comment]
Sorry, I could have articulated that better. I don't know how much work it is for you packaging and releasing 7.5.2. It would be nice to have the fix in version 7 as the release schedule says it will be around a while. Clicking the rebase buttons is the easy part. :-D

**Comment by epdenouden** [comment]
@sebastianbergmann If you have time, can you also merge this into `master` already? I'm working on some more housekeeping in `tests/` and I'd handy to have the newer bootstrap :)

**Comment by sebastianbergmann** [comment]
Done. Sorry for forgetting this.

**Comment by epdenouden** [comment]
No worries, thank you for the quick response! In the past I've had some merge/rebase uhmmm confusion and I wanted to prevent any self-conflicts 😬

**Pull request merged**
