### PR TITLE
Fix: Do not show help when `failOnEmptyTestSuite` is `false`

### LINKED ISSUE #5192: Running an empty test shows help screen
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 10.0.7
| PHP version         | 8.1.4
| Installation Method | Composer

#### Summary

After upgrading from `phpunit/phpunit:9.6.3` to `phpunit/phpunit:10.0.7` running `phpunit` with a `phpunit.xml` that points to a directory that does not contain any tests succeeds, but shows the help screen.

#### Current behavior

Running `phpunit` with a `phpunit.xml` that points to a directory that does not contain any tests succeeds, but shows the help screen.

#### How to reproduce

See https://github.com/ergebnis/symfony-application-template/pull/1544, and give me a few moments to open a pull request.

#### Expected behavior

Running `phpunit` with a `phpunit.xml` that points to a directory that does not contain any tests succeeds with warnings.

### PR DESCRIPTION
**Pull request by localheinz**
This pull request

- [x] stops showing the help screen when `failOnEmptyTestSuite` is `false`

Fixes #5192.

### CODE REVIEW

**Comment by sebastianbergmann** [comment]
Please send this against `10.0`.

**Comment by localheinz** [comment]
@sebastianbergmann 

Rebased!

The problem we have now is that tests that expect that the help screen is shown fail because the help screen is not shown anymore. 

Do you have an idea how we can sort this out?

**Comment by sebastianbergmann** [comment]
Please do not change [tests/end-to-end/cli/help.phpt](https://github.com/sebastianbergmann/phpunit/pull/5195/files#diff-61d7116fdbd98b01d78ce4939b6d282e1d6e38d724911a2fc6f05315f274f47c). The point of this test is to verify that `phpunit` prints the help output when no test suite is configured and the  `--help` option is not used.

**Comment by localheinz** [comment]
@sebastianbergmann 

Before `phpunit/phpunit:10.0.0`, an empty test suite would not fail. Since `phpunit/phpunit:10.0.0`, an empty test suite fails with the help screen and a non-zero exit code.

**Comment by sebastianbergmann** [comment]
Thank you for your contribution. I appreciate the time you invested in preparing this pull request. However, I have decided not to merge it as it is the wrong fix.

**Pull request closed without merging**
