### PR TITLE
Fix "fsockopen(): Unable to connect to hostname:0" warning

### PR DESCRIPTION
**Pull request by staabm**
refs https://github.com/sebastianbergmann/phpunit/pull/5779#issuecomment-2027951918

regression caused by https://github.com/sebastianbergmann/phpunit/commit/727d2fd6b5e8bed6dd07fb1f22362f3e9f73dd9d

### CODE REVIEW

**Comment by sebastianbergmann** [comment]
Still getting this on macOS:
```
❯ ./phpunit
PHP Warning:  fsockopen(): Unable to connect to hostname:0 (Failed to parse address "hostname") in /Users/sb/Work/OpenSource/phpunit/src/TextUI/Output/Printer/DefaultPrinter.php on line 86

Warning: fsockopen(): Unable to connect to hostname:0 (Failed to parse address "hostname") in /Users/sb/Work/OpenSource/phpunit/src/TextUI/Output/Printer/DefaultPrinter.php on line 86
PHPUnit 11.1-gb9dd1c68e by Sebastian Bergmann and contributors.
```

**Comment by staabm** [comment]
Ha, will have another try later. Sorry :-)

**Comment by staabm** [comment]
I can have a look this evening

**Comment by sebastianbergmann** [comment]
> I can have a look this evening

This has time after the holidays. Enjoy your weekend!

**Pull request merged**
