### PR TITLE
Improve Composer's settings on Travis

### PR DESCRIPTION
**Pull request by henriquemoody**
Related to #1607.

### CODE REVIEW

**Comment by henriquemoody** [comment]
I think it didn't make difference: check it out:

> Failed to download sebastian/version from dist: You must enable the openssl extension to download files via https
> Now trying to download from source

Composer installed all package by source.

**Comment by GrahamCampbell** [comment]
That's a bummer. Travis must have disabled it in the env update. :(

**Comment by GrahamCampbell** [comment]
> Composer installed all package by source.

No, that's only for php 5.3.3. Travis has that extension disabled due to security concerns.

**Comment by henriquemoody** [comment]
Whatever, on other versions we get:

> Could not authenticate against github.com
> Now trying to download from source

I remember long time ago, I use to get the same error but Composer didn't have this fallback.

**Comment by GrahamCampbell** [comment]
Yeh, don't worry about that. It just means travis has bust the api limit for the moment. It will start working at some point. :)

**Comment by henriquemoody** [comment]
I know, that, that's why I started using `--prefer-source`.

The same is happening to phpspec and others who doesn't use this.

**Comment by GrahamCampbell** [comment]
Hmmm.

**Comment by henriquemoody** [comment]
Since it's unnecessary I'm closing this.

**Pull request closed without merging**
