### PR TITLE
Some minor performance optimizations

### PR DESCRIPTION
**Pull request by willemstuursma**
* Use strict `in_array()` so that the new `ZEND_IN_ARRAY ` opcode can be used
* Use splat operator instead of `func_get_args()` where applicable.

### CODE REVIEW

**Comment by sebastianbergmann** [comment]
Please send two separate pull requests. The refactoring to use the splat operator needs to wait until PHPUnit 8 due to BC considerations.

**Comment by willemstuursma** [comment]
OK, will get to it later this week. 

>  The refactoring to use the splat operator needs to wait until PHPUnit 8 due to BC considerations.

What breaks because of this change? The `Constaint` type is checked a bit later anyway. Just curious.

**Comment by sebastianbergmann** [comment]
There is no semantic change, but a syntactic one as the signature of the methods changes.

Whether or not it is a good idea to overwrite PHPUnit's "built-in" assertions (it's not) in your test case classes, changing their signature is a BC break and existing tests will cease to work due to signature mismatches.

**Comment by sebastianbergmann** [comment]
Cherry-picked https://github.com/sebastianbergmann/phpunit/pull/3145/commits/6b04697d2b1800f6f48b07a9124bc5888d26c511 into `master`.

**Comment by willemstuursma** [comment]
> Whether or not it is a good idea to overwrite PHPUnit's "built-in" assertions (it's not) in your test case classes. 

They could be made `final` in PHPUnit 8.

**Comment by sebastianbergmann** [comment]
Yes, that is an idea I would like to pursue.

**Pull request closed without merging**
