### PR TITLE
Enhancement: Use built-in PHP 7.3 to speed up build for 8.3

### PR DESCRIPTION
**Pull request by localheinz**
This PR

* [x] uses the built-in binary for PHP 7.3 to run jobs on  on `8.5.`

Follows #3809, #3820, #3823.

### CODE REVIEW

**Comment by sebastianbergmann** [comment]
Thanks! Can you have a look that I did not break anything by mergin this into `master`?

**Comment by localheinz** [comment]
@sebastianbergmann 

Will do!

**Comment by localheinz** [comment]
@sebastianbergmann 

Running `roave-backward-compatibility-check` [fails](https://github.com/sebastianbergmann/phpunit/runs/215960959#step:3:1), but I think that should be expected!

👍

**Comment by sebastianbergmann** [comment]
No, it should not fail. And it no longer does: https://github.com/sebastianbergmann/phpunit/runs/215965976

**Pull request merged**
