### PR TITLE
Export constants values when mocking method

### PR DESCRIPTION
**Pull request by gleb-svitelskiy**
Fix for issue https://github.com/sebastianbergmann/phpunit/issues/3801
Contributors should consider to change minimum supported PHP version

### CODE REVIEW

**Comment by sebastianbergmann** [comment]
What do you mean by "Contributors should consider to change minimum supported PHP version"?

**Comment by gleb-svitelskiy** [comment]
This problem because of PHP bug https://bugs.php.net/bug.php?id=76717. Fix was released in versions 7.2.17 and 7.3.4. But latest version of PHPUnit requires `"php": "^7.2"` in composer. And `version_compare('7.2.0', PHP_VERSION, '>')` in phpunit file. So it can be used on versions from 7.2.1 to 7.2.16, and from 7.3.1 to 7.3.3 where PHP bug #76717 still there.
```
gleb@svitelskiy:~$ docker run --rm php:7.2.16 php -r 'var_export(PHP_INT_MIN);echo "\n";'
-9223372036854775808
gleb@svitelskiy:~$ docker run --rm php:7.2.17 php -r 'var_export(PHP_INT_MIN);echo "\n";'
-9223372036854775807-1
gleb@svitelskiy:~$ docker run --rm php:7.3.3 php -r 'var_export(PHP_INT_MIN);echo "\n";'
-9223372036854775808
gleb@svitelskiy:~$ docker run --rm php:7.3.4 php -r 'var_export(PHP_INT_MIN);echo "\n";'
-9223372036854775807-1
```

**Comment by gleb-svitelskiy** [comment]
> What do you mean by "Contributors should consider to change minimum supported PHP version"?

This problem because of PHP bug https://bugs.php.net/bug.php?id=76717. Fix was released in versions 7.2.17 and 7.3.4. But latest version of PHPUnit requires `"php": "^7.2"` in composer. And `version_compare('7.2.0', PHP_VERSION, '>')` in phpunit file. So it can be used on versions from 7.2.1 to 7.2.16, and from 7.3.1 to 7.3.3 where PHP bug #76717 still there.
```
gleb@svitelskiy:~$ docker run --rm php:7.2.16 php -r 'var_export(PHP_INT_MIN);echo "\n";'
-9223372036854775808
gleb@svitelskiy:~$ docker run --rm php:7.2.17 php -r 'var_export(PHP_INT_MIN);echo "\n";'
-9223372036854775807-1
gleb@svitelskiy:~$ docker run --rm php:7.3.3 php -r 'var_export(PHP_INT_MIN);echo "\n";'
-9223372036854775808
gleb@svitelskiy:~$ docker run --rm php:7.3.4 php -r 'var_export(PHP_INT_MIN);echo "\n";'
-9223372036854775807-1
```

**Comment by sebastianbergmann** [comment]
Merged manually, thanks.

**Pull request closed without merging**
