### PR TITLE
8.x-branch: update Windows CI to use latest PHP 7.2 minor

### PR DESCRIPTION
**Pull request by epdenouden**
Updating AppVeyor CI to use new download location for latest PHP minor versions

### CODE REVIEW

**Comment by epdenouden** [comment]
@sebastianbergmann The CI complains about something an xdebug thing now, is this related to the recent code coverage changes/discussions?

**Comment by epdenouden** [comment]
Same thing with the PHPUnit 7.5.x-branch and the AppVeyor update: https://github.com/sebastianbergmann/phpunit/pull/3485

**Comment by sebastianbergmann** [comment]
Looks like https://github.com/sebastianbergmann/phpunit/blob/master/src/Util/Filesystem.php#L33 does not work for `php://stdout` on Windows.

**Comment by sebastianbergmann** [comment]
https://github.com/sebastianbergmann/phpunit/commit/d03987cfe13b02565758afd24cca2cee4c0e4170 should fix this.

**Comment by epdenouden** [comment]
Underway now, will try and fix both when I get home

**Comment by epdenouden** [comment]
@sebastianbergmann thanks!! :)

**Pull request merged**
